### ISSUE TITLE
Scene file

### ISSUE THREAD

**Issue by ivangorelow** [tangrams/tangram-es#1031]
I use android SDK. Can I update scene file from JAVA code?

**Comment by ivangorelow** [comment]
I'd like to change vanishing_point

**Comment by tallytalwar** [comment]
Hey

You can use the [queueSceneUpdate](https://github.com/mapzen/android/blob/master/library/src/main/java/com/mapzen/android/graphics/MapzenMap.java#L580) and [applySceneUpdates](https://github.com/mapzen/android/blob/master/library/src/main/java/com/mapzen/android/graphics/MapzenMap.java#L587) to update scene file from android sdk.

As an example you can refer to [this](https://github.com/tangrams/tangram-android-demos/blob/master/sceneupdates/src/main/java/com/mapzen/tangram/demos/sceneupdates/MainActivity.java), which is an example using core android tangram-es API, but APIs from mapzen android sdk should work exactly the same.

**Comment by ivangorelow** [comment]
Can I change this parametrs? true and false
> labels-global:
    - &allParkings         false
    - &notAllParkings      true

**Comment by bcamper** [comment]
@ivangorelow you cannot change those because they are YAML anchors/references, which are evaluated on initial parsing. However, we are in the process of converting our styles to use Tangram's own [`global`](https://mapzen.com/documentation/tangram/global/) to solve this and provide more flexibility.

@tallytalwar is the upgraded Bubble Wrap using global properties in the current SDK version?

**Comment by tallytalwar** [comment]
@ivangorelow as @bcamper mentioned you can change YAML anchors/references from the SDK.

@bcamper The latest release of [Android SDK](https://github.com/mapzen/android/releases/tag/v1.1.0) is using [this](https://github.com/tangrams/bubble-wrap/tree/4d79430dba93709151dca056a11bec704a56b50d) version of bubble-wrap style, which is using our `global` references instead of YAML anchor/reference.

**Comment by bcamper** [comment]
Great. @ivangorelow give that a try and let us know you have any issues.

**Comment by ivangorelow** [comment]
Thank you. It works. I use my own YAML file
