### ISSUE TITLE
MapController::getPosition return LngLat with negative Longitude

### ISSUE THREAD

**Issue by westnordost** [tangrams/tangram-es#1097]
Tangram-ES Version 0.4.5

MapController::getPosition and MapController::screenPositionToLngLat may return a LngLat in which (at least) the longitude is negative.

I got this above Hamburg, when having the map centered at lat=53,58220643220753, lon=9,939129168887803. Lon was -350.0608708311122 instead.

I know this is still mathematically correct, but having a coordinate whose longitude is not within the -180°..+180° bounds is certainly unexpected. If you intend to not fix this by normalizing the angle, it would be good if this were documented.

**Comment by blair1618** [comment]
Oh, haha that's fair. It's probably more convenient for everyone if we return longitudes within (-180, 180] and say that in the documentation for the getter.

**Comment by westnordost** [comment]
Fun fact: 
My app made lon=-350.0608708311122 into lon=***7***9,939129168887803 until I fixed this bug right now https://github.com/westnordost/osmapi/commit/16691490a7be8a187fde052d6db0b3e1f1ff316f

**Comment by ac87** [comment]
I should point actually not wrapping allowed had a side effect of allowing lines to be drawn across the international dateline. Since I raised a duplicate bug on the exact issue addressed here perhaps I should have added this before

See this freehand drawing example (just me drawing a random wave):

Before fix
![2017-09-26 14_30_42-clipboard](https://user-images.githubusercontent.com/20557626/30862954-9ad6656c-a2c7-11e7-8977-ebf150e8c685.png)
After fix
![2017-09-26 14_28_28-clipboard](https://user-images.githubusercontent.com/20557626/30862960-9eea058c-a2c7-11e7-9e8d-59cd7b1d2adc.png)

I know this fix is better for most scenarios, but maybe some applications will want to work as before. At this point I'm still just playing with Tangram-es to see what can be done. Freehand drawing works pretty well with markers.

**Comment by tallytalwar** [comment]
@ac87 thats a valid argument, maybe we can expose the API such that the user has the flexibility of getting a wrapped longitude or an unwrapped longitude (controlled by a boolean)? And by default we always return wrapped longitude.

**Comment by matteblair** [comment]
I don't think it will be helpful to add an option for getting an explicitly "unwrapped" longitude, as this concept isn't guaranteed to be preserved if we change the implementation of world-wrapping. Lines with segments that cross 180 degrees longitude will be correctly displayed using a `MapData` instance, so I'd recommend using that for cases like this.

**Comment by ac87** [comment]
I'm not sure a drawing use case works with MapData or at least I haven't seen something dynamic enough to allow variable thickness and any color. I do appreciate the world-wrapping situation though, its currently not ideal with markers, without a jump to my location button taking you to the 'primary' world you can get lost.
