### ISSUE TITLE
Inconsistency with JS on text_source fallback

### ISSUE THREAD

**Issue by nvkelso** [tangrams/tangram-es#1108]
We discovered in https://github.com/tangrams/paparazzi/issues/12 that there is an inconsistency between JS and ES around the handling of `text_source` values when not using the default. This is causing a significant rendering bug on styles like Refill under ES.

It seems like Tangram ES is evaluating as if it is: `text_source: [name:short, name]` even though I've specified it as: `text_source: name:short`.

@blair1618 noted that this seems like a bug in ES as specifying `text_source: 'name:short'` (which should be equivalent here to `text_source: name:short`) produces the same behavior as in JS.

Specifically, on Refill most the light grey region text labels on the map shouldn't be displayed at zoom 4.

**JS correct**
![JS correct](https://cloud.githubusercontent.com/assets/853051/20542024/92a03522-b0b4-11e6-881a-5fa109c5842d.png)

**ES bug, look in Columbia**
![ES bug](https://cloud.githubusercontent.com/assets/346914/20681043/c6272152-b56f-11e6-8ebc-aca59240c6ad.png)

See also:

- https://github.com/tangrams/refill-style-more-labels/blob/gh-pages/refill-style-more-labels.yaml#L4121-L4133
- The visible on Tangram ES region names source their text from name:short via this global:
  -https://github.com/tangrams/refill-style-more-labels/blob/gh-pages/refill-style-more-labels.yaml#L22-L25
- In ES code we are setting the text's source default as the name property.
https://github.com/tangrams/tangram-es/blob/master/core/src/style/textStyleBuilder.cpp#L292
- https://github.com/tangrams/tangram-docs/blob/1d0d68a14b6548c71778cd2aa529aa3ddea0399e/pages/draw.md#text_source

**Comment by tallytalwar** [comment]
Ok this is convoluted:

Some explanation of what is happening here:

For features with no `name:short` property, `evalStyle` results in `false` [here](https://github.com/tangrams/tangram-es/blob/ea2c9c63845bd81b3ba4259e771b95fe02c15d40/core/src/scene/drawRule.cpp#L182).

Now this marks this rule as inactive [here](https://github.com/tangrams/tangram-es/blob/ea2c9c63845bd81b3ba4259e771b95fe02c15d40/core/src/scene/drawRule.cpp#L187).

Now in `textStyleBuilder` while applying the rules, `!_rule.isJSFunction(StyleParamKey::text_source)` if condition is satisfied because `isJSFunction` calls `findParameter` which checks for a parameter's [active state](https://github.com/tangrams/tangram-es/blob/ea2c9c63845bd81b3ba4259e771b95fe02c15d40/core/src/scene/drawRule.cpp#L85). 

Hence eventually the code path leads to https://github.com/tangrams/tangram-es/blob/master/core/src/style/textStyleBuilder.cpp#L292, which is when `name` property is returned.

**Comment by tallytalwar** [comment]
All the above steps are correct for all other style parameters.

A quick fix might be to not mark the rule inactive when the key is `text_source` and the function evaluates to `none`?

**Comment by bcamper** [comment]
@tallytalwar so to confirm, this does sound like an ES bug, is that right?

**Comment by tallytalwar** [comment]
Yes.
