### ISSUE TITLE
Tangram texture atlases management

### ISSUE THREAD

**Issue by nvkelso** [tangrams/tangram-es#1145]
Picking up from https://github.com/tangrams/bubble-wrap/pull/218....

Many mobile graphics chips expect `1024` width by `1024` height max textures, but our icon textures for house styles are all bumping up against this limit now.

Is there a way for Tangram to construct it's own **paginated texture** from the loaded artwork asset before passing it to the GPU? 

This shouldn't be the artists concern constructing the texture, and with more icons and more road shields planned, we need a system that's extensible just for Mapzen house styles.

**Comment by nvkelso** [comment]
Current texture sizes after they were re-packed to stay within 1024px bounds.

* **Bubble Wrap**: `1,006` x `994`
* **Refill**: `1,016` x `846`
* **Tron**: `1,010` x `1,000`
* **Walkabout**: `1,016` x `990`

Collectively there are around 300 icons, but any one texture has only 230-250. Geraldine and I had been planning on filling in the holes so they were standardized – but there's not much wiggle room here on total dimensions.

**Comment by nvkelso** [comment]
There's a 3 pixel gap between assets now, but standard size is 18px * 2 pixels per px. Taking that down to 2 px does save some space on Tron (`976` height), but negligible on Walkabout.

**Comment by blair1618** [comment]
I agree that scene authors shouldn't need to worry about this kind of technical limitation, but automatically splitting a texture is a very tricky thing for the engine to do. I would be more inclined to make an open-source offline tool for generating atlases and sprite definitions.

Before we invest any effort into this, however, I'll try to get some real numbers on how many devices this limitation impacts.

**Comment by matteblair** [comment]
Been a while since I thought about this one! OK so:

1. A large majority of devices support at least 2048 pixel textures now. OpenGL ES 3 requires 2048 as the minimum GL_MAX_TEXTURE_SIZE and almost 80% of current Android devices comply with this (many exceed it) https://developer.android.com/about/dashboards/

2. If we need even larger textures or want to support super low-end devices I still think this makes more sense as an offline tool, rather than an engine feature. 

Closing!
