### ISSUE TITLE
Crash in rendering thread when adding multiple markers

### ISSUE THREAD

**Issue by Guillaume227** [tangrams/tangram-es#1227]
I have been playing with code that adds a few dozens markers in a loop in one function call and I am getting very frequent crashes in the GL thread which is attempting to render partially set markers
(I am not talking about different threads concurrently adding markers).
I haven't digged very deep yet but based on the Android example code (and the c++ interface code below) I haven't seen any mutex I should lock when creating markers.
Is that a known limitation ?

I have seen that @matteblair comment in the PR in which markers where introduced back in september which might allude to what's causing my problem:
_I've kind of punted on synchronization for markers at present. If we care about thread safety here then there's a lot we'll need to guard - so let's make that a follow-up task._

**Comment by matteblair** [comment]
Can you share the code that's producing these crashes (particularly the c++ interface)?

**Comment by Guillaume227** [comment]
I understood what's going on in my code:

I am adding a few dozens markers then wipe them out and add a new batch.
It's the wiping out that's causing the trouble with the render thread: as that thread iterates over std::unique_ptr<marker> some have been removed by my application thread and became null.

I see there is not mutex for markers like there is for tiles to protect access to markerManager.markers().

So it's crashing in places like this (tangram.cpp, around line 490)
       ```
  for (const auto& marker : impl->markerManager.markers()) {
                if(marker)
                    style->draw(impl->renderState, *marker);
            }
```

And in places where we check the ease etc.

**Comment by matteblair** [comment]
Ok I think I understand. In our Android interface, most application logic happens on the UI thread while rendering happens on the GL thread. To guard against concurrent access, most of our JNI methods are designated `synchronized`. For other platform targets, there's no need to incur those synchronization costs so we don't perform synchronization inside the core library. Tile sets, however, _must_ be synchronized in the core library because we access them from worker threads.

For Android applications that don't go through the Java interface we provide, you would need to provide your own synchronization mechanism to prevent concurrent access from the UI thread and GL thread.

Does this answer your questions?

**Comment by Guillaume227** [comment]
Makes sense, thanks! I am going to add synchronization on my end then.
I feel this should really be pushed down to the c++ API though as it's a cross platform concern.
Maybe it will get introduced as part of #1034 then.
