### ISSUE TITLE
Recommend using subtree instead of submodule for externals.

### ISSUE THREAD

**Issue by lygstate** [tangrams/tangram-es#1233]
Submodule maintaining is a big pain.:(....

**Comment by matteblair** [comment]
Yes submodules can be a burden at times - especially when switching between branches! However once they are set up, submodules do have the advantage of being much easier for pushing changes upstream than subtrees.

For some of the dependencies that we frequently modify, like `alfons` and `yaml-cpp`,  it is important that we are able to very easily make changes and push them upstream, so some dependencies will remain as submodules for that purpose. For other dependencies that we do not frequently update, like `glfw` and `glm`, we could replace their submodules with simple copies of the necessary source files. This has been discussed here: https://github.com/tangrams/tangram-es/issues/1212

**Comment by tallytalwar** [comment]
We have reorganized a lot of our code structure to use subtrees for some dependencies, and as mentioned by @matteblair above, for some projects it is much convenient to keep these as submodules. To further help your cause, we also cleaned some of our dependencies so that we do not have to maintain recursive submodules (refer: https://github.com/tangrams/tangram-es/pull/1304).

I am closing this for the time being.
