### ISSUE TITLE
Android webview and Tangram support

### ISSUE THREAD

**Issue by am2222** [tangrams/tangram-es#1255]
Hi,
Does anyone knows if androids webview supports tabgram or not?As far as I know it does not support WebGL in older versions. So does it make tangram maps does not show?

**Comment by matteblair** [comment]
Hello!

It seems that WebGL is supported on newer versions of the Android WebView sofware, but won't be available on versions before Android 5.0 (https://developer.chrome.com/multidevice/webview/overview). The tangram JS library also uses Web Workers, which may not be supported in Web View. tangram-es is designed specifically as a more efficient solution for map rendering on Android, so obviously I recommend using tangram-es, but if you try the JS library I would be very curious to hear how it goes!

**Comment by am2222** [comment]
Hi @matteblair 
I have already tried JS library and it workes on android 5 above but every time I must clear the catch to show map, I have no idea if it is because of tangram or something else. 
How can I find features of tangram-es? I want to draw routes and users location and rotation. I have no Idea if tangram-es supports it or not?

**Comment by matteblair** [comment]
Glad to hear the WebView works! I don't have any guesses why the cache would impact tangram though.

A convenient way to use tangram-es on Android is the [Mapzen Android SDK](https://github.com/mapzen/android), which includes location services and overlays. You can find all the documentation on our website: https://mapzen.com/documentation/android/

**Comment by am2222** [comment]
@matteblair ,Hi,
You know I want to use my own services for navigation, basemap, etc so as I looked at those documentations I can't use mapzen's services duo to their own specifications. The main things that I am looking for is drawing user current position, drawing route which is consumed of a service which returns jeojson, drawing a 3d shape of building which comes from a service in geojson format and adding interaction (like click, zoom,rotation) on map, All of those is currently applied in my web version using JS but I can't load it on android lower than 5.0

**Comment by ac87** [comment]
I wouldn't try to use Tangram JS on Android when Tangram-ES exists.

[Eraser Map](https://github.com/mapzen/eraser-map) [(Google Play)](https://play.google.com/store/apps/details?id=com.mapzen.erasermap) is the best demonstrator of the Tangram capability on Android. 

This [repository](https://github.com/ac87/tangram_android) demonstrates a number of things you are after without Mapzen's SDK:
- Change Basemap to Raster map tiles from a different source (assets/raster/source.yaml)
- Device GPS location [(this commit)](https://github.com/ac87/tangram_android/commit/0ddc0e2c33fb93a2088e94b38542c692bbbe5239)
- Simple Route from list of Lat/Lons [(this commit)](https://github.com/ac87/tangram_android/commit/56971aa20ad7070a57775c36f3f3817fefe49382)

_Note: I'm not a Tangram or Mapzen Developer, just trying to be helpful since I've done these things recently. The markers are relatively new so examples are a bit limited, even Eraser map in the Play store isn't using the 'flat' style attribute on my location yet._

**Comment by am2222** [comment]
@ac87 wow thank you, It seems the only remaining thing is about marker animations.I hope It is possible to do it. thanks

**Comment by ac87** [comment]
@am2222 See update. I was using setPosition instead of setPositionEased. That said it causes some weird behavior using setPositionEased, so I might be using it wrong. #1264

**Comment by am2222** [comment]
@ac87 thanks very much for your great information

**Comment by matteblair** [comment]
Great answer! You are correct that the Mapzen Android SDK provides location and routing using our own hosted services. It's certainly possible to use your own services for these (you can even model it on the Mapzen SDK), it will just take a bit more work.

Do you have more questions about using tangram-es for rendering?
