### ISSUE TITLE
Using Marker Animation causing run away view Re-rendering.

### ISSUE THREAD

**Issue by ac87** [tangrams/tangram-es#1264]
See this sample app and in particular this [commit ](https://github.com/ac87/tangram_android/commit/dfcfb974b85667fecc450ddef22979c6457aa35d)

If `myLocationMarker.setPointEased` is used, the `MapController.ViewCompleteListener()` registered in `MainActivity ` gets called constantly ("View complete" appearing in the LogCat). This would be expected for 200ms but not constantly after.

Stopping the location updates doesn't stop it either.

**Comment by matteblair** [comment]
Hi again, thanks for the report. From the code here and your description this does sound like a bug - the view should only re-render continuously for the duration of the easing. 

I will try to replicate this behavior and see if I can find a work-around for you while we fix it.

**Comment by matteblair** [comment]
Haha whoops - it looks like Marker easing is currently interpreting the time parameter as _seconds_ when it should interpret it as _milliseconds_, so the Markers are actually moving continuously - just very very slowly. That's our bad :\

We'll get this fixed in the next release but until then you can just divide your Marker easing times by 1000.
