### ISSUE TITLE
Add tangram ios documentation

### ISSUE THREAD

**Issue by tallytalwar** [tangrams/tangram-es#1266]
And publish it aptly under https://mapzen.com/documentation/tangram/

cc. @karimnaaji @msmollin

**Comment by msmollin** [comment]
For auto-generated code docs, tools options include:
- https://github.com/tomaz/appledoc ( The reliable choice )
- http://www.stack.nl/~dimitri/doxygen/ (old and deprecated for obj-c)
- https://github.com/realm/jazzy (new hotness)

I would recommend looking at Jazzy first as that's where much of the community focus has been recently.

As far as format for API, there's a frustrating divergence in the community. Objective-C APIs still seem to use the Headerdoc format (https://developer.apple.com/legacy/library/documentation/DeveloperTools/Conceptual/HeaderDoc/tags/tags.html), which is Javadoc styled, whereas Swift seems to prefer a newer Markdown-style approach (http://ericasadun.com/2015/06/14/swift-header-documentation-in-xcode-7/). So for ES since we're using objective-c we'll wanna go with Headerdoc for now, until Apple changes their minds :)

**Comment by karimnaaji** [comment]
Doxygen is quite heavy and for its deprecation I think that we can take it out of the list.
I think that Jazzy is the most promising so far, some initial testing using it for the framework:

![screen shot 2017-02-07 at 4 06 15 pm](https://cloud.githubusercontent.com/assets/7061573/22714758/f24b348e-ed5b-11e6-8731-d93df03eac28.png)
