### ISSUE TITLE
iOS pickMarker rarely called when touch Marker's location

### ISSUE THREAD

**Issue by seubseub** [tangrams/tangram-es#1284]
Hi

I have a issue for pickMarker method.
`func mapView(_ view: TGMapViewController, recognizer: UIGestureRecognizer, didRecognizeSingleTapGesture location: CGPoint) {
        
        view.pickMarker(at: location)
        view.pickLabel(at: location)
        view.pickFeature(at: location)
        let loca = screenPosition(toLngLat: location)
        print("latitude\(loca.latitude)")
        print("longitude\(loca.longitude)")
        
        
    }`
This method make pickMaker function call
And I set Marker like this.
```
markerSetStyling(Marker, styling: "{ style: 'points', interactive : true,  color: 'white', size: [30px, 30px], order: 1200, collide: false }")                    

markerSetImage(Marker, image: UIImage(named: "marker")!)

markerSetPoint(Marker, coordinates: TGGeoPoint(longitude: mylng, latitude: mylat))
```
So when I try pick marker, marker rarely selected....

so I think may pick marker called by exact location's latitude and longitude

Could you help me this issue?

Thank you.

**Comment by karimnaaji** [comment]
By the way our selection system works, it is not possible that you pick for the exact maker's location latitude and longitude, it should be a least the size of your marker, so in your case `30px`x`30px`.

Have you tried experimenting with different values of [setPickRadius](https://github.com/tangrams/tangram-es/blob/master/ios/src/TGMapViewController.h#L148)? It is basically a _thumb size_ that would increase the size of your selection. It is possible that since the selection is pixel perfect by default, you have some trouble selecting small markers like yours.

**Comment by seubseub** [comment]
Thanks It works! I didn't set setPickRadius. so default value  0.5 is set.
Anyway thank you! @karimnaaji

**Comment by karimnaaji** [comment]
Nice! Closing this.
