### ISSUE TITLE
Mobile devices: Always get bitmaps from dp dependent resources

### ISSUE THREAD

**Issue by westnordost** [tangrams/tangram-es#1372]
(Feature request/discussion:)

Would it not make sense to make it the default on Android to get the images referenced in the scene file from the `Resources` and on iOS from the assets in the main bundle respectively, just as it is done with markers?

**Comment by matteblair** [comment]
Maybe!

A couple things make this difficult:

 - It's unclear how one would reference these from the scene file, since they don't have 'file paths' in a traditional sense. We could come up with something, but it's extra complication that we've avoided so far.
 - Native code doesn't have direct access to these resources. So even once we know the resource that we want to use, we would have to call into some platform-specific code that retrieves the bitmap, copies it into a memory location that the native code can access, and then returns that memory to the native code. 

It wouldn't be impossible to implement, but the effort and complication has always seemed to outweigh the possible benefit (for Markers this is easier because the relevant code is already in a platform-specific layer).

**Comment by nvkelso** [comment]
Related discussion in Tangram JS repo:

- https://github.com/tangrams/tangram/issues/438

**Comment by westnordost** [comment]
>for Markers this is easier because the relevant code is already in a platform-specific layer
Ah I see. I thought this was a low-hanging fruit after the marker implementation, so that's wrong.

The effort then seems to very much outweigh the gain to make the assets really conform to the "Android way" of asset managing, the @2x is fine too. I'll close this feature request, then.
