### ISSUE TITLE
Marker.setVisible(boolean) function does not work properly.

### ISSUE THREAD

**Issue by JunsuLime** [tangrams/tangram-es#1390]
Marker.setVisible(boolean) function doesn't work properly.

I thought the marker would not always be visible or invisible when this function was called. But when i manipulate the map, it doesn't work properly.

When the Visibility false setting is initially set, it works normally. However, if I move the map to the point where there is no marker and then return to first position where the setVisible (false) marker exist again, the marker is shown on map.

And The odd thing is that when zooming again, it looks like it was not visible.

i want your help T_T

**Comment by ivangorelow** [comment]
I have the same problem

**Comment by tallytalwar** [comment]
Hi

I am reproduce this on my end in the default osx app. Will update with a fix .

**Comment by karimnaaji** [comment]
@tallytalwar the fix for that is to separate the visible property used for label collision purposes and the one used for marker visibility. Since they are both the same right now, it seems that when the label gets out of screen it goes to from `out_of_screen` -> `visible` state without assuming the visibility could have been forced for a marker.
