### ISSUE TITLE
iOS(swift) - TGMapdata clear

### ISSUE THREAD

**Issue by seubseub** [tangrams/tangram-es#1405]
Hi :) I'm using tangram iOS

And I'm trying to remove line, but when TGMapdata.clear, then my app die.

Android is almost same as my code, and I already test at your demo iOS(Objective C) app. 

but Android work well, also demo app can remove TGMapdata.

So I want to know about my mistake or something.

here is my code about this problem.

first, I make variable.
`var lineMakers : TGMapData!`

and addDataLayer
`self.lineMakers = self.addDataLayer("AA")!`
`self.requestRender()`

and this is add polyline code
```
if(lastPoint != nil) {
            
                
                var props = [String : String]()
                props["type"] = "line"
                props["color"] = "#D2655F"
                
                let line = TGGeoPolyline()
                line.add(lastPoint!)
                line.add(currentPoint)
                
                lineMakers.add(line, withProperties: props)
                
            }
            lastPoint = currentPoint
```

And finally This is clearLine() source
```
   func clearLine() {
        print("lineMakers \(lineMakers)")
        print("lineMakers.map \(lineMakers.map)")
        lineMakers.clear()
        self.requestRender()
        

    }
```

when i print TGMapData.map it print nil value.

I'm curious about my code. Did I do wrong thing?

Thank you for reading my issue :)

**Comment by karimnaaji** [comment]
Hey @seubseub,

This code looks legal to me.

The bug actually lives our `TGMapData.h`, we have different naming for the property `map` in the public interface and private interface (it is called `map` in the public header and `mapView` in the private one, which is the one being set).

We will make sure to fix this issue for the next release, for a safe code for now you should be able to use this custom map data without accessing the property `map`. Thanks for the catch :) 
This Should be fixed with https://github.com/tangrams/tangram-es/pull/1408.

As a note for better usage of our API:

You shouldn't have to call `requestRender` yourself, you should only have to call this in a pattern like this, where the view inherits from `TGMapViewController`:

```objc
- (void)requestRender:
{
    [super requestRender];
    // Other render dependent code for this view
}
```
Otherwise, the map view controller will handle the render requests automatically.

**Comment by seubseub** [comment]
@karimnaaji Thank you for kind replying!

I'll wait for tangram next release :)
