### ISSUE TITLE
[Discussion] Rethink TGMarker <-> TangramMap interaction model.

### ISSUE THREAD

**Issue by msmollin** [tangrams/tangram-es#1442]
While writing my response to #1440 I started thinking about the interaction model between TGMarker and the map that displays it. Rather than pollute that ticket further I wanted to open a larger discussion which I think will lead to rearchitecting that dependency model a bit.

Markers really have very little to do with a map, when you think about it. Markers are just a set of metadata, location, and styling information about something on the map. That could be a device's current location, or a POI, or a tappable highway shield, etc. The map takes that information, and renders it for display (same as with vector tiles). 

Ultimately this means the coupling between our existing TGMarker and TangramMap does little more than complicate the interaction model between the two. We should mimic the interface off of the model "A map displays a marker".

There are 2 possible developer workflows currently for TGMarkers being added to a map:

1) Developer creates instance of `TGMarker`
2) Developer sets the map instance that owns the `TGMarker` on the marker itself
3) Developer sets the rest of the options which at some point in the future take effect.

**OR**

1) Developer creates instance of `TGMarker`
2) Developer sets the options they want.
3) Developers sets the map instance that owns the `TGMarker` with an implicit "opt-in" that by setting this instance, they would like the marker to be displayed on the map.

There's a logical separation here which didn't really showcase itself in the original PR, but has showed up on usage in the Mapzen iOS SDK. The API as it stands now is not explicit with the intent to display a marker. A developer sets the map instance (https://github.com/tangrams/tangram-es/blob/427b70422640343410c7c395708001814df9a465/platforms/ios/src/TangramMap/TGMarker.mm#L269) and through a series of "side effects" from setting that map instance, the marker may or may not get displayed.

What I suggest is we flip the interaction model such that rather than setting TGMapViewController instances on one or more TGMarkers, we tell TGMapViewController to display one or more TGMarkers. 

I think this has a number of benefits:
1) We condense down to one workflow which mimics the second original workflow in its steps, but instead of setting a map instance on the marker, the developer explicitly tells the map to render and display their marker(s). 
2) From a performance perspective, we're only going to render once the developer is ready to render that data. This avoids some unnecessary rendering churn that could occur from the original first workflow.
3) We can rather drastically simplify the internal implementation of TGMarker by centralizing the error management code inside TGMapViewController and just having the marker return those errors like currently implemented: only if it's been added to a map.

This way, we can preserve the dynamic re-rendering currently possible with TGMarker (which I think is fairly neat) and still have an expressive error system while at the same time moving the API to be more declarative and explicit with its intent.

Thoughts?

**Comment by msmollin** [comment]
Thanks to @karimnaaji for the initial prototype of this. I think we have a pretty clear idea of a path forward now on this after more internal discussion.

So the current front-runner is an interface modeled more after CRUD-style operations

Pseudocode:
```
---Interface addition to TGMapViewController---
- (BOOL)addMarker:(TGMarker *)marker withError(NSError**)error{
//Move all error checking currently done inside TGMarker here
}

- (BOOL)updateMarker:(TGMarker *)marker withError(NSError**)error{
}

(BOOL)deleteMarker:(TGMarker *)marker withError(NSError**)error{
}
```

This would change the interaction model away developers interacting directly with TGMarker, and instead treat TGMarker more like just a data object. This centralizes all the error management with the map controller which honestly seems better since that also manages communication with the internal TangramMap instance.

A few questions are outstanding on that interface:
- Can we combine `addMarker` and `updateMarker` into one function? This would create something akin to the `Update-if-exists` model that's popular in web APIs but might not make sense here?
- Do we want to diverge the Tangram iOS SDK away from how the other clients work into a more transactional update model?

Also, @sarahlensing expanded on this idea a bit by adding additional specific data objects for things like `Polyline` and `Polygon`. This could use additional exposition but seems like it could provide an eventual outlet for additional shapes.

Also there was a fleeting idea of creating a `TGMarker Protocol` which would allow custom TGMarkers to be created by end users. Not sure if this is useful or not but given Apple's focus on "Protocol Oriented Programming" it might be good to define one regardless even if we don't immediately consume it.

**Comment by sarahlensing** [comment]
Thats a good summary of where we're at. I'll just add some detail about the expansion @msmollin mentioned. My suggestion was to move error handling into the specific classes in which errors can arise from...so for example:

```objc
@interface TGStyleString : NSObject

- (instancetype)init();

- (BOOL)setStyling:(NSString *)str withError:(NSError**)error;

@end


@interface TGMarker

@property (readonly, nonatomic) TGStyleString* styleString;

@end


TGMarker *marker = [[TGMarker alloc] init];
TGStyleString *styleStr = [[TGStyleString alloc] init];
NSError *error;
if (![styleStr setStyling:@"example-styling" withError:error]) {
  //handle error
}
marker.styleString = styleStr;
```

This approach would allow the `TGMarker` properties to remain simple getters/setters but it wouldn't necessarily condense all the error handling into one location. But, if we don't want to commit to a transactional model, it would allow us to avoid doing so.

**Comment by karimnaaji** [comment]
> I'll just add some detail about the expansion @msmollin mentioned. My suggestion was to move error handling into the specific classes in which errors can arise from...so for example:

@sarahlensing I'm not sure to see what would be the value in comparison to what is proposed in #1448? Where usage is the following:
```swift
marker = map.markerAdd();
if (!marker.setStylingString(stylingString, &error)) {
  // handle error
}
```

Since, the nice part of what is proposed by @msmollin is that the error handling is condensed to a single call, here we would have single object for geometry / styling that handles error handling by themselves instead of having a single call that figures out errors. 

It is also not really possible with the core tangram API; creating a styling string and get errors from it without associating it to a marker object is not something we can do currently, so you wouldn't be able to actually get those errors from only a styling string (without having to create a marker identifier).

Though, I agree that in what is proposed the error handling is moved away from the actual statement that sets the styling string / geometry to a marker:
```swift
marker.setPolygon(polygon);
marker.setStylingString(stylingString);
if (!map.updateMarker(marker, &error)) {
  // Error handling happens at this time, find out what went wrong
} 
```
So the context about what triggers the error can be lost.

If the error handling is important to the context (e.g. you need to know the error at the time you set either a geometry or a marker, I would stick with the API of #1448). Otherwise, if it is acceptable to use the marker as a data holder, _commit_ the changes to the map and only have an error at the time of this commit, then we should pursue further with this proposal.

**Comment by sarahlensing** [comment]
@karimnaaji The value is that the errors are more closely tied to the objects that can generate them. So without platform specific knowledge, the readability would feel more natural...ie. when I create a `StylingString` object from a raw string, the validity of the raw value would be checked. With the current proposal in #1448, the errors are generated at a later point in the flow when the styling string is set on the marker which feels less natural. 

```
It is also not really possible with the core tangram API; creating a styling string and get errors from it without associating it to a marker object is not something we can do currently, so you wouldn't be able to actually get those errors from only a styling string (without having to create a marker identifier).
```
If this proposal is something we would want, I'm curious how feasible is it to restructure the core tangram API so that it's possible?

Regarding @msmollin 's proposal, we could return an array of errors (but that isn't very idiomatic). Or, we could recommend that developers call the `addMarker` method after every call which can generate an error if they care about context.

**Comment by karimnaaji** [comment]
>If this proposal is something we would want, I'm curious how feasible is it to restructure the core tangram API so that it's possible?

Thinking around this; we would need to add core API call in order to validate a styling string without a marker identifier being created

```c++
bool stylingStringValidate(const char* _styling);
```
which will potentially load the required styling string as a YAML node for parsing errors, then check whether the style is available in the current scene, compile the possible javascript functions etc.. (it happens [here](https://github.com/tangrams/tangram-es/blob/master/core/src/marker/markerManager.cpp#L309_L384), where we interact  with the marker itself in order to set the draw rule data).

Then we would still have our 
```c++
bool markerSetStylingFromString(MarkerID _marker, const char* _styling);
```
which will associate this styling string to the marker; at this point we will still need to build the draw rule anyway since `stylingStringValidate` would be stateless regarding to the marker, and potentially make the same work twice.

>Regarding @msmollin 's proposal, we could return an array of errors (but that isn't very idiomatic). 

Do you know whether this reflect appropriately in Swift?

>Or, we could recommend that developers call the addMarker method after every call which can generate an error if they care about context.

This seems a little extreme, I would rather not have to suggest that in the usage of tangram-es markers.

**Comment by karimnaaji** [comment]
Here is a recap of the options that we have:

```c++
// Prototype
TGMarker marker = map.addMarker();
marker.setPolygon(polygon, &error);
marker.setStyling(styling);

// Tangram 6.0
TGMarker marker = [TGMarker init] / [TGMarker initWithMapView:view]
marker.setPolygon(polygon, &error); 
marker.setStyling(styling);
marker.setView(view, &error);

// Transaction-like
TGMarker marker = map.addMarker();
marker.polygon = polygon; // don't call tangram
marker.styling = styling;
map.updateMarker(marker, &error); // calls tangram

// Get error style
TGMarker marker = map.addMarker();
marker.polygon = polygon; // actually calls tangram
marker.styling = styling;
marker.getError(&error); // (get an error code stored as a bitset or anything that can represent several errors)
```
Unless something is drastically proven wrong with the `getError` style we will move forward with this one, since it seems to be the best alternative that we have: 
- keeps the properties on the Swift side, so less code changes on the SDK
- leaves the ability to get the error without losing the context if the user wants to
- setting the property would directly reflect the changes on the marker unlike the transaction-like

**Comment by matteblair** [comment]
Either of the "transaction" or "get error" approaches seem reasonable to me. If there's a consensus on the "get error" syntax then I agree with moving ahead on it.

**Comment by tallytalwar** [comment]
Yup me and @karimnaaji discussed the `getError` approach with @sarahlensing and @msmollin on thursday. Going with that only.

**Comment by tallytalwar** [comment]
Some of the work being done here: https://github.com/tangrams/tangram-es/pull/1466 (cc. @karimnaaji)
