### ISSUE TITLE
Map wraparound/"Infinite scrolling" for raster sources

### ISSUE THREAD

**Issue by Jiangyi** [tangrams/tangram-es#1456]
First of all, let me just say what an awesome project this is! Props to all you guys for the tremendous work you have put in. :-)

I'm looking at implementing a raster world map on Android reading from an mbtiles source, but I noticed that with raster sources, the map does not "wrap around" at the left and right edges, as it would if the source was in MVT format. Instead, the raster tiles would be rendered on screen once (when the tile loads), and never again when scrolling to a longitude that should correspond to one of the already loaded tiles. This behaviour can also be seen in the Android demo app when using one of the raster YAML scene files.

Is there a way to achieve this wraparound/infinite scrolling behaviour? And if this is not currently implemented, could you guys kindly give me some pointers as to how to start implementing this? Don't really mind getting my hands dirty here heh. Thanks!

**Comment by matteblair** [comment]
Hi @Jiangyi, thanks for the report! I can reproduce this problem in the latest release. 

Wrapping around the 180th meridian is enabled by default, and if you try this with a vector tile source you'll see that it works as expected. However, it seems that there is a bug in the way this is applied to raster tiles now. It appears to me that a raster tile is only ever being shown at the first location where it is requested and not shown at any of the other "wrapped" locations. 

I can't say without looking more closely where the root of this problem is - but one of us on the core team will be looking into it shortly.

**Comment by Jiangyi** [comment]
Oh cool, thanks for the quick response @matteblair! Looking forward to any future updates :)

**Comment by matteblair** [comment]
This issue should be fixed by #1458 in the next release. Thanks @tallytalwar for the quick fix and @Jiangyi for finding this bug :+1:

**Comment by Jiangyi** [comment]
Thank you guys so much! Much appreciated. :)
