### ISSUE TITLE
assert crash with applySceneUpdates and sceneAssets

### ISSUE THREAD

**Issue by Guillaume227** [tangrams/tangram-es#1473]
I am hitting the assert at sceneLoader.cpp:587 following a call to applySceneUpdates();
That's because it's looking for a texture url in scene->sceneAssets().
That texture asset was properly loaded during the loading of the scene.
However that line at he end of in SceneLoader::loadScene:
`    _scene->sceneAssets().clear();
`
clears the loaded assets.

I am trying to understand the logic of calling clear at that stage in relation to the applySceneUpdates calls that may follow.
Map displays fine if I do not call applySceneUpdates()

Any idea?

**Comment by tallytalwar** [comment]
Yup, this seems to be a bug in the recently merged PR (https://github.com/tangrams/tangram-es/pull/1373) which does not handle scene assets loaded from initial scene load aptly when applying scene updated. 

Since this PR was merged after 0.6.1 release, this bug does not manifests in any of tangram-es official releases.

**Comment by Guillaume227** [comment]
@tallytalwar : thank you !
