### ISSUE TITLE
duplicate lines cause different result in tangram-es and tangram play

### ISSUE THREAD

**Issue by matkoniecz** [tangrams/tangram-es#1584]
**TO REPRODUCE THE ISSUE, FOLLOW THESE STEPS:**

 - List the steps you used
 - To produce the result here
 - Don't leave any out

use style with

```
                     stroke: { color: black, width: 1 }
                     stroke: { color: global.text_stroke, width: [[1,1px], [12,2px],[16,4px]] }
```

**RESULT:**

Describe the result here.

first line is used

As result, following map style change https://github.com/matkoniecz/StreetComplete/commit/d1bc84f77e8695530a18803aaa9b862b678e890c causes change to rendered map with tangram-es interpreter

tangram play in both cases is using second stroke definition.

**EXPECTED RESULT:**

Describe what you expected to see here.

either

- second line is used (as redefinition)
- error is raised
- both tagram play and tangram-es are using first line and ignore redefinition

**ENVIRONMENT:**

 - What operating system and device did you produce this issue on?
 - If you used a released version, what is the version number?

- Redmi 4 Xiaomi
- Android 6.0.1 MMB29M
- com.mapzen.tangram:tangram:0.7.1

**OTHER:**

Any additional notes, comments, tips, tricks, gifs, suggestions, poetry, recipes, jokes

If you are able to record the log output from tangram-es, please attach it as a text file or share it using a site like https://hastebin.com/

Reported here as ignoring first line and using second as redefinition seems saner interpretation of repeated rules.

Though giving error message would be preferable in both interpreters.

**Comment by matteblair** [comment]
The scene file excerpt you've posted is invalid YAML: repeated keys in a mapping are not allowed (http://www.yaml.org/spec/1.2/spec.html#id2802432).

However as you've suggested, Tangram ES and Tangram Play could be more helpful in this situation. To your suggestions:

  1. Use the second line as re-definition: There is no concept of ordering in a YAML mapping so we can't meaningfully call one of these lines the "second" one.
  2. Error is raised: This would be a helpful behavior, if we can get Tangram ES and Tangram Play to error in the same ways.
  3. Use the first line and ignore re-deifintion: Again, because mappings are inherently unordered, we can't call one of them "first".

Thanks for creating a matching issue for this in Tangram Play, I'll see if there's a feedback mechanism for this that will work for both engines.

**Comment by westnordost** [comment]
I think the most helpful would be to reject the style definition entirely (2.) because it is obviously an error.

**Comment by matteblair** [comment]
Tangram is able to report many YAML syntax errors, but this one in particular isn't detected by the YAML parsing library we use. There are good reasons why it doesn't, but it's kind of a long story: https://github.com/jbeder/yaml-cpp/issues/60

To diagnose issues like this in the future, a separate YAML syntax validator may be the easiest solution. Gonna close this issue.
