### ISSUE TITLE
GLSurfaceView on top of map does not render (tangram-ES 0.8.0-RC2)

### ISSUE THREAD

**Issue by westnordost** [tangrams/tangram-es#1619]
I tested out **tangram-ES 0.8.0-RC2** on [this branch](https://github.com/westnordost/StreetComplete/tree/tangram-0.8) for StreetComplete.

Changes made to get from 0.7 to 0.8:
https://github.com/westnordost/StreetComplete/commit/302968ea2c62e329596fcf1f19365f6f4ac8c539

### Bug description

I display a GLSurfaceView on top of the map which renders a compass needle on white background. In 0.8.0-RC2, the complete GLSurfaceView is transparent and blank, nothing is rendered. 
The mentioned GLSurfaceView is [this class](https://github.com/westnordost/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/view/CompassView.java).

**Comment by westnordost** [comment]
I tested it on two devices so far:
* Sony D5503, Android 5.1.1 (API 22):  reproducable
* Emulator (API 26): can't reproduce

**Comment by matteblair** [comment]
Thanks, we're going to look into this before finalizing 0.8.0. Do you have an APK from your branch that we could put on other devices to test?

**Comment by westnordost** [comment]
Ehm, right now not because I want to go to bed and my internet connection is very slow right now.

**Comment by matteblair** [comment]
Figured out the issue here, no changes are needed in Tangram ES.

**Short answer:**

Call `setZOrderMediaOverlay(true);` in `CompassView$init()` and it will draw as expected.

**Long answer:**

Android `SurfaceView`s are not like regular `View`s, they cannot be arbitrarily ordered and composited in a hierarchy. There are a fixed number of "Z" values that a surface view can render with, and by default all `SurfaceView` instances (i.e. both our `MapView` and your `CompassView`) render to the same "Z". One will render after the other and "win", but it's undefined which it will be if they are at the same "Z". You can put a `SurfaceView` above the default "Z" with `setZOrderMediaOverlay` (https://developer.android.com/reference/android/view/SurfaceView.html#setZOrderMediaOverlay(boolean)) to ensure that it consistently "wins".

For way too much background, you can check out this document on Android graphics architecture (https://source.android.com/devices/graphics/architecture)

**Comment by westnordost** [comment]
I see, thank you!

**Comment by westnordost** [comment]
This solved the issue.
