### ISSUE TITLE
Add shadow mapping to renderer

### ISSUE THREAD

**Issue by grefab** [tangrams/tangram-es#1635]
To enhance visual appearance of the map I'd like to suggest adding **shadow mapping** like e.g. [here](http://googlemapsmania.blogspot.de/2014/06/the-creeping-shadow-on-map.html) for data sources with **extruded buildings**. Seems like first steps in that direction have been taken by [@karimnaaji](https://twitter.com/karimnaaji), see examples [here](https://twitter.com/karimnaaji/status/644987040489185280) and [here](https://twitter.com/karimnaaji/status/878659433345241088).

Is anything shadow-related currently planned or in progress? Do you support/object the idea?

**Comment by matteblair** [comment]
Hi @grefab, thanks for the interest and apologies for leaving this unanswered. 

We have also been keen on the idea of shadow mapping for 3D geometry! I also really like those examples by Karim.

When we've thought about this feature in the past, a few things arise that make shadows difficult:

 - Tangram is built around an extremely customizable pipeline - users can literally write the GLSL shaders used to render the scene. This means we can't make many assumptions about the shading pipeline, we'd have to give users control over the application of shadows if we wanted it to work well in all scenarios.
 - Tangram runs on a very wide range of hardware, and not all the target devices support things like depth textures (which makes shadow mapping much simpler). To implement shadows well, we'd probably need to implement multiple pipelines for different device capabilities. 

In the end, since Tangram maps are typically more focused on clarity and flexibility than on photo-realism, we're not going to prioritize shadow mapping in the near future.

(However, if someone else figured out a nice implementation we certainly wouldn't mind ;) )

**Comment by karimnaaji** [comment]
>Tangram runs on a very wide range of hardware, and not all the target devices support things like depth textures (which makes shadow mapping much simpler). To implement shadows well, we'd probably need to implement multiple pipelines for different device capabilities.

For future references or anyone interested in this support for Tangram, I'll draft the pipeline I had for shadow mapping that can be inspired of. It appears to be working quite nicely on a wide range of hardware so far, and solves some of the issues mentioned.

- Lack of depth texture support or floating point texture: for this the trick to pack the depth data into a color texture (since writing to texture is to my knowledge, usually well-behaving on any ES 2.0 hardware), and unpack when sampling the depth. This 'packing' pass to generate the depth texture only needs to be generated when tiles are added or deleted (It is not necessary to run every frame).

GLSL code to pack depth data:
```glsl
// Stores the 24 bits depth value in each 8 bits components, depth between 0..1
vec3 packDepth888(float depth) {
    vec3 packedDepth;

    packedDepth.x = depth * 65536.0;
    packedDepth.y = depth * 256.0;
    packedDepth.z = depth;
    packedDepth.x = fract(packedDepth.x);
    packedDepth.y = fract(packedDepth.y) - packedDepth.x / 256.0;
    packedDepth.z = fract(packedDepth.z) - packedDepth.y / 256.0;

    return packedDepth;
}
// used as gl_FragColor= vec4(packDepth888(gl_FragCoord.z), 1.0);
```

Debug view of such a texture:
<img width="502" alt="screen shot 2017-11-15 at 16 10 37" src="https://user-images.githubusercontent.com/7061573/32860423-91dbfa2e-ca1f-11e7-8fac-e37c28eec1fc.png">

When reading from it:
```glsl
float unpackDepth888(vec3 depthRGB) {
    return depthRGB.r / 65536.0 + depthRGB.g / 256.0 + depthRGB.b;
}
float texture2DCompare(sampler2D depths, vec2 uv, float compare) {
    return step(compare, unpackDepth888(texture2D(shadowMap, uv).rgb));
}
float getShadow(sampler2D shadowMap, float shadowBias, vec4 shadowCoord) {
    vec2 uv = shadowCoord.xy * 0.5 + vec2(0.5);
    float shadowCoordDepth = (0.5 * shadowCoord.z + 0.5) - shadowBias;
    if (uv.x < 0.0 || uv.y < 0.0 || uv.x >= 1.0 || uv.y >= 1.0) { return 1.0; }
    return texture2DCompare(shadowMap, uv, shadowCoordDepth);
}
```

- Lack of NPOT texture, instead of making a framebuffer with an attached texture of the size of the viewport, simply shrink it to a 512x512 texture to have support over a wider range of devices. At sampling time, shadow artifact can appear (Also refer https://software.intel.com/en-us/articles/dynamic-resolution-rendering-on-opengl-es-2). 

- Shadow artifact, use a bias and increase shadow map resolution: the goal to do so is to 'fit' the cuboid volume of the shadow caster to the scene area, sample code for this:

<img width="397" alt="screen shot 2017-11-15 at 16 09 11" src="https://user-images.githubusercontent.com/7061573/32861452-b782dab0-ca22-11e7-9849-fa5d4069e171.png">


```c++
// Assuming boundingBox encompasses the whole set of visible tiles for the current viewport:
FrustrumFit fit(BBox boundingBox, glm::vec3 sunDirection) {
    glm::vec3 up = glm::vec3(0.0, 0.0, 1.0);
    glm::vec3 center = glm::vec3(0.0);
    glm::vec3 at = -sunDirection;
    glm::mat4 view = glm::lookAt(at, center, up);

    // Kill translation component
    view[3][0] = 0.0;
    view[3][1] = 0.0;
    view[3][2] = 0.0;

    glm::vec3 BBoxCorners[8] {
        glm::vec3(boundingBox.max.x, boundingBox.min.y, boundingBox.min.z),
        glm::vec3(boundingBox.max.x, boundingBox.min.y, boundingBox.max.z),
        glm::vec3(boundingBox.max.x, boundingBox.max.y, boundingBox.min.z),
        glm::vec3(boundingBox.max.x, boundingBox.max.y, boundingBox.max.z),
        glm::vec3(boundingBox.min.x, boundingBox.min.y, boundingBox.min.z),
        glm::vec3(boundingBox.min.x, boundingBox.min.y, boundingBox.max.z),
        glm::vec3(boundingBox.min.x, boundingBox.max.y, boundingBox.min.z),
        glm::vec3(boundingBox.min.x, boundingBox.max.y, boundingBox.max.z),
    };

    BBox cameraSpaceBBox;
    for (int i = 0; i < 8; ++i) {
        glm::vec3 cameraSpaceBBoxPoint = view * glm::vec4(BBoxCorners[i], 1.0);
        cameraSpaceBBox = merge(cameraSpaceBBox, cameraSpaceBBoxPoint);
    }

    // Camera looking at -z
    double far = std::max(-cameraSpaceBBox.min.z, -cameraSpaceBBox.max.z);
    double near = std::min(-cameraSpaceBBox.min.z, -cameraSpaceBBox.max.z);

    glm::mat4 projection = glm::ortho(
        (double)cameraSpaceBBox.min.x,
        (double)cameraSpaceBBox.max.x,
        (double)cameraSpaceBBox.min.y,
        (double)cameraSpaceBBox.max.y,
        near, far);

   return { projection, view };
}
```

<img width="566" alt="screen shot 2017-07-26 at 16 15 44" src="https://user-images.githubusercontent.com/7061573/32860688-6330abf6-ca20-11e7-83db-855c97711c6a.png">

**Comment by tallytalwar** [comment]
Thanks @karimnaaji
