### ISSUE TITLE
2x tap should zoom in

### ISSUE THREAD

**Issue by nvkelso** [tangrams/tangram-es#1648]
Now only two finger zoom works (or pinch zoom)

2x currently recanters the map – I find that weird.

**Comment by nvkelso** [comment]
Doesn't work in demo app downloaded as latest from ios.mapzen.com :/

**Comment by rugk** [comment]
Ah okay, I am on Android, but the behaviour should be the same AFAIK.

**Comment by matteblair** [comment]
You're referring to the OS X demo application, yes? The responses to gesture input are in the demo application code, which is a little different for each platform. It would be very simple to do a zoom on double-tap instead of the current behavior. Since it's less of a user-facing product, we didn't think very hard about the input in this demo. Any other ideas are :+1: too.

**Comment by matteblair** [comment]
Resolved by #1614
