### ISSUE TITLE
3d rendering of specific building fails

### ISSUE THREAD

**Issue by rugk** [tangrams/tangram-es#1653]
**TO REPRODUCE THE ISSUE, FOLLOW THESE STEPS:**

I used the app [StreetComplete](https://github.com/westnordost/StreetComplete), which uses [tangram 0.8.0](https://github.com/westnordost/StreetComplete/blob/040ae0ee0bec68fc7654bd42c687eb448e928495/app/build.gradle#L99).

**RESULT:**

On particular building fails to render in the 3d mode. When rotating/moving it flickers between grey and this type of brown:
![color](https://user-images.githubusercontent.com/11966684/30444437-42966534-9983-11e7-8946-b73287927634.png)

**EXPECTED RESULT:**

Proper 3d rendering

**ENVIRONMENT:**

Cyanogenmod 14/Android 7

**OTHER:**

I can send you a video and the place where it happens via mail.

Ref: https://github.com/westnordost/StreetComplete/issues/592

**Comment by nvkelso** [comment]
What approximate map location (zoom, lat, long)? Is this still using
Cinnabar style?

**Comment by rugk** [comment]
Drop me a mail and I can send you more information. And yes, Cinnabar style.

**Comment by nvkelso** [comment]
Email sent.

**Comment by nvkelso** [comment]
We think this is related to a vector tile bug: https://github.com/tilezen/vector-datasource/issues/1226.

Basically that building is duplicated between two neighboring tiles and the way the `landuse_kind` is calculated it doesn't always result in the same exact value per tile for the same feature. Because of the two states per tile and the overlap between tiles, it z-fights.

So not something wrong in the style or Tangram.

**Comment by tallytalwar** [comment]
The issue here is because the underlying data has missing `landuse_kind` tag at certain zoom level. Our vector tiles project already has an issue created for this. Kindly refer to https://github.com/tilezen/vector-datasource/issues/1226 for more details.

Leaving this issue open until https://github.com/tilezen/vector-datasource/issues/1226 gets resolved.

**Comment by matteblair** [comment]
This isn't an issue that can be resolved in tangram - closing.
