### ISSUE TITLE
Address build issues with sqlite3 for ndk 15+

### ISSUE THREAD

**Issue by tallytalwar** [tangrams/tangram-es#1660]
Currently we are including deprecated headers to avoid running into sqlite build issues with ndk 15.2+. But we will have to address this issue sooner than later as these headers will be excluded in the future ndk versions.

Reference: https://android.googlesource.com/platform/ndk/+/ndk-r15-release/docs/UnifiedHeaders.md
Sqlite3 issue on android ndk project: android-ndk/ndk#477

**Comment by cleeus** [comment]
Right on time. I just got bitten by this.
I tried to build on iOS11. On iOS the OS-version of sqlite is used, which comes in a newer version which requires a newer SQLiteCpp because of slight header incompatibilities. So I tried to update SQLiteCpp. SQLiteCpp 2.2.0 comes with sqlite-3.20.1 bundled. When building on Android this fails because the new sqlite uses mmap.

I was able to fix/work around this by adding
target_compile_definitions(sqlite3 PRIVATE -DSQLITE_MAX_MMAP_SIZE=0 -DSQLITE_OMIT_WAL)
to the core/deps/SQLiteCpp/sqlite3/CMakeLists.txt. This disables the use of mmap in sqlite3. I'm not sure of this is the right fix.

**Comment by tallytalwar** [comment]
Thanks @cleeus. This could be good, will try it out. Thanks

**Comment by 4brunu** [comment]
I was having the same issue, and this is what fixed for me.
https://github.com/couchbaselabs/couchbase-lite-libsqlcipher/pull/23

**Comment by tallytalwar** [comment]
Resolved by #1667
