### ISSUE TITLE
tangram:0.9.0-RC1 do not start on arm64-v8a

### ISSUE THREAD

**Issue by fokin33** [tangrams/tangram-es#1736]
In app.gradle
 compile 'com.mapzen.tangram:tangram:0.9.0-RC1'
If run arm64-v8a build, get:
java.lang.UnsatisfiedLinkError: 
  at java.lang.Runtime.loadLibrary (Runtime.java:367)
  at java.lang.System.loadLibrary (System.java:1076)
  at com.mapzen.tangram.MapController.<clinit> (MapController.java:1162)
  at com.mapzen.tangram.MapView.getMapInstance (MapView.java:49)
  at com.mapzen.tangram.MapView.getMap (MapView.java:41)
If run armeabi-v7a on same device it start OK.

**Comment by matteblair** [comment]
Can you explain specifically what you mean by "run arm64-v8a build"? What steps or gradle commands should we use to reproduce this?

**Comment by fokin33** [comment]
splits {

        // Configures multiple APKs based on ABI.
        abi {

            // Enables building multiple APKs per ABI.
            enable true
            reset()

            // Specifies a list of ABIs that Gradle should create APKs for.
            include "x86", "armeabi-v7a", "arm64-v8a", "armeabi"

            // Specifies that we do not want to also generate a universal APK that includes all ABIs.
            universalApk false
        }
    }
    project.ext.versionCodes = ['armeabi': 1, 'armeabi-v7a': 2, 'arm64-v8a': 3, 'mips': 5, 'mips64': 6, 'x86': 8, 'x86_64': 9]

    android.applicationVariants.all { variant ->
        variant.outputs.each { output ->
            output.versionCodeOverride =
                    project.ext.versionCodes.get(output.getFilter(
                            com.android.build.OutputFile.ABI), 0) * 10000000 + android.defaultConfig.versionCode
        }
    }

**Comment by matteblair** [comment]
Ah thanks! I think I understand the problem now.

In 0.9.0-RC1 we have reduced the number of ABIs provided by Tangram ES. It now provides only `x86` and `armeabi-v7a` (see details and explanation here: https://github.com/tangrams/tangram-es/pull/1664). 

For your build configuration, I will first say that the `armeabi` ABI is deprecated in the current NDK and will soon be removed (https://developer.android.com/ndk/guides/abis.html#sa), so in my opinion you can remove that split.

However, it seems like the split for `arm64-v8a` is producing an APK that is missing a `libtangram.so` (not surprising, since no `arm64-v8a` version of `libtangram.so` exists in the AAR). I'm afraid the only solution to this right now would be to remove the `arm64-v8a` split from your builds. The `armeabi-v7a` split should run perfectly well on any `arm64-v8a` devices, but I understand that some applications can benefit from targeting the `arm64-v8a` ABI specifically - so this isn't ideal.

The changes to our ABI support in #1664 didn't consider applications using APK splits, so this has made me reconsider some of those changes.
