### ISSUE TITLE
Feature request, Compile tangram-es to WebAssembly & running in browser.

### ISSUE THREAD

**Issue by lygstate** [tangrams/tangram-es#1761]
So we could replace tangram with tangram-es and only a single copy of code need to be maintained.
And in future, we also can compiling tangram-es to WebAssembly -> JVM bytecode, so we could running in Android without the .so files.

**Comment by matteblair** [comment]
I would like to experiment with compiling to WASM!

However, I don't think that's going to provide a very good replacement for tangram-js. First, tangram-es in WASM will be much much larger than tangram-js because tangram-es implements a lot of things that a browser can do for you (like text layout and networking requests). Second, WASM wouldn't provide a convenient interface for say, Leaflet, the way that tangram-js does. 

I also don't see how Android would benefit from WASM. Converting WASM to JVM bytecode seems pretty experimental and would be totally impossible to debug. Surely a few .so files bundled in an AAR aren't so bad :)

**Comment by andreamancuso** [comment]
@matteblair I suppose you still have zero interest in compiling tangram-es to WASM? I'm looking to embed a map component into my GLFW3+WebGPU based React bindings. I am out of my depth.
