### ISSUE TITLE
Feature Request: Counterpart to getEnclosingCameraPosition

### ISSUE THREAD

**Issue by westnordost** [tangrams/tangram-es#1959]
Since forever, the `MapController` used to have the following two methods:

* `LngLat screenPositionToLngLat(PointF)`
* `PointF lngLatToScreenPosition(LngLat)`

Now, since 0.10, there is the very useful 👍 method

* `CameraPosition getEnclosingCameraPosition(LngLat, LngLat, Rect)`

However, a counterpart for it, to get the currently shown bounding box in LngLat coordinates is missing. The output could be any rotated trapezoid if there is tilt or rotation, so it would be something like

* `LngLat[] getEnclosedBoundingBox(CameraPosition, Rect)`

### Use Case

My use case is that I want to pull data from another source for the shown part of the map.

**Comment by westnordost** [comment]
Actually, this can be achieved with only a few lines of code using the existing methods, so maybe not that important. So I withdraw that feature request.

**Comment by matteblair** [comment]
Thanks for the feedback! I totally agree it's useful to be able to easily get the bounds of the current view. The trick is, like you said, what to do when the view is rotated or tilted. Getting a list of trapezoid vertices could be useful for some cases, but in many situations a bounding box would probably be more appropriate. Since there wasn't an obvious answer at the time we put off adding this feature till later.
