### ISSUE TITLE
Anti-aliasing effect is not obvious, not as good as mapbox effect, how to improve?

### ISSUE THREAD

**Issue by liugang1014** [tangrams/tangram-es#2067]
I run the demo app on iphone7 device and mac book pro,Sawtooth on the edge is more serious
,Anti-aliasing effect is not obvious, not as good as mapbox effect, how to improve?

![image](https://user-images.githubusercontent.com/5100512/59411158-2fc95500-8ded-11e9-8e0c-6c6c605a8a73.png)

**Comment by matteblair** [comment]
We actually do not apply any anti-aliasing to the framebuffer in Tangram! In iOS this is configured here: https://github.com/tangrams/tangram-es/blob/master/platforms/ios/framework/src/TGMapView.mm#L223 If you instead set this value to [GLKViewDrawableMultisample4X](https://developer.apple.com/documentation/glkit/glkviewdrawablemultisample/glkviewdrawablemultisample4x?language=objc) then you would see anti-aliased geometry edges. This option negatively impacts performance on older devices, which is why it is normally not enabled in Tangram.

**Comment by liugang1014** [comment]
@matteblair thanks a lot,turn on msaa4x got a good effect.
