### ISSUE TITLE
iOS Annotation view

### ISSUE THREAD

**Issue by MarkoBG** [tangrams/tangram-es#2082]
Hello,

Is there an option to display annotation view or popup info view when a user touches a marker on a map? I would like to achieve some similar behavior as Apple done with MapKit.
I see I can add a new view to the map, but I don't know how to anchor that view near the marker. Because if you drag or zoom in on a map, the annotation view will remain in the same place and the marker will move away with the map.

Environment:
1. Xcode 10.3
2. Swift 5
3. Tangram-es 0.10.1

Thank you.

**Comment by matteblair** [comment]
Hi @MarkoBG, I meant to reply to this issue sooner and I forgot - sorry about that. Tangram ES currently does not have any function to attach a UIVIew to a point on the map. This is a feature I've wanted to add for a while but have not gotten around to implementing yet.

Did you close the issue because you found a solution to this or are you simply not interested any more?

**Comment by MarkoBG** [comment]
Hi @matteblair, I have found some solution, but still did not accomplish behaviour that I wanted. I use UIBezierPath class to draw annotation view and delegate methods for pan and pinch gestures to track coordinates of marker. 
Annotation view is behave weird, because I calculate the position of the annotation view based on the coordinates of the marker and then when dragging the map it looks as the view is chasing the marker. If you have any suggestions how to handle this, I would be grateful.
