### ISSUE TITLE
MapController.lngLatToScreenPosition returns point 0,0 for certain parameters

### ISSUE THREAD

**Issue by westnordost** [tangrams/tangram-es#2165]
**REPRODUCTION:**

Here is an example state for which it is reproducible.

Call `MapController.lngLatToScreenPosition` for

- `latitude = 37.80455166666666`
- `longitude = -122.30210333333335`

whilst the camera is at

- `latitude = 37.8034503901695`
- `longitude = -122.30177937658814`
- `rotation = 3.4500046`
- `tilt = 0.62831855`
- `zoom = 19.624928`

It incorrectly returns a point with

- `x = 0`
- `y = 0`

The used smartphone is a Sony Xperia Z1 Compact, in case screen size and pixel density play a role in this. If you want to reproduce it with a different device and you can't with these values, try zooming in further or moving the camera.

**EXPECTED BEHAVIOR:**

Here is an example state where it works. **Note, ALL the parameters are exactly the same as above, except that the zoom is a little lower.** So, the two examples are each at the edge of "result is correct" and "result is wrong". Hope that helps. 

Call `MapController.lngLatToScreenPosition` for

- `latitude = 37.80455166666666`
- `longitude = -122.30210333333335`

whilst the camera is at

- `latitude = 37.8034503901695`
- `longitude = -122.30177937658814`
- `rotation = 3.4500046`
- `tilt = 0.62831855`
- **`zoom = 19.341661`** <- this changed

It returns a point with

- **`y = 16659.263671875`** <- correct resultnow
- **`x = -1016.594482421875`**

**ENVIRONMENT:**

- Android 5.1, Sony Xperia Z1 Compact, tangram-es 0.12.0

**FURTHER INFORMATION:**

- It is not (only) related to the zoom level. In fact, if changing the rotation, the tilt or position offset beyond a certain value, the calculated point becomes correct again.
- **I could only ever reproduce it if the tilt is not 0**

**Comment by westnordost** [comment]
(I added two more perhaps helpful observations to the further information section. Also if you would like to have something visual, follow the linked bug)

**Comment by westnordost** [comment]
If you would like an example app for which you could play around with tilt, zoom, rotation etc while `MapController.lngLatToScreenPosition` is constantly called on each map movement with a clear visual indication if a calculation was wrong, you can take the current master of StreetComplete and do the following:
1. (Use your debug build of tangram-es instead of the maven dependency.)
2. Move the map away from your position, so that the pointer pin at the edge of the screen is visible (current GPS position necessary). If the pointer pin points exactly at the upper left edge of the screen, the point calculation returned 0,0 and you reproduced the bug.
3. Tilt the map (two-finger-gesture or click on the compass). I was never able to reproduce the issue with a non-tilted map
4. Rotate and/or zoom in the map further until you can reproduce the issue. You could set a condition breakpoint that only triggers if 0,0 is about to be returned

**Comment by matteblair** [comment]
Ok, I'm able to reproduce these results under certain conditions and I know what's happening in the code. This isn't exactly a bug. It's intentional behavior, but there may be a way to make this less confusing.

This condition occurs when the point that you are trying to project to screen space is currently _behind_ the camera plane. This can never happen when the camera has zero tilt (as you observed) because that keeps the camera plane parallel to the ground. However if the camera plane is tilted and placed very close to the ground (e.g. at a high zoom) then it becomes possible for points on the ground to be behind the camera plane. 

When this happens, the world-to-screen projection operation is no longer meaningful - there is not a good mathematical answer to "where does this point project in screen space?". There is a check for this condition in Tangram ES: https://github.com/tangrams/tangram-es/blob/master/core/src/util/geom.cpp#L96 We chose to return `{0, 0}` somewhat arbitrarily - no alternative seemed clearly better:
- Return `NaN`s? Nobody likes `NaN`s, and we don't want to check for them everywhere
- Do the conversion anyway and return the result? The screen space value will approach infinity and then flip signs, which isn't a useful result to anyone.

I'll have to think more about what behavior would be most useful here, but an easy improvement we could make now is to let programmers detect when this condition occurs. Similar to the internal function I linked above, `lngLatToScreenPosition` could indicate when the result is "clipped".

**Comment by westnordost** [comment]
Hmm, interesting. So assuming a tilt of 45°, camera pointing north at lat 0, lon 0, would that mean that for all all the points on the Southern hemisphere, the algorithm would return 0,0?

I wonder what values one could expect if the result is not clipped?

**Comment by matteblair** [comment]
You'd only clip the southern hemisphere if the camera were at exactly zero altitude (effectively infinite zoom). The "clipped" condition is quite uncommon in typical use, but of course having enough users will lead to finding every edge case :)

**Comment by matteblair** [comment]
MapKit and GoogleMaps have APIs for this too, so I checked their behavior in this situation. Both of them choose to return the "un-clipped" result regardless of whether the location falls behind the camera plane. So if you were using GoogleMaps or MapKit in this situation, you would get a screen position that's mirrored across the camera plane from the "expected" position (e.g. if your camera were pointing North, your resulting screen position would have the sign of the Y coordinate flipped).

It would be simple for Tangram to do the same thing for consistency, but this wouldn't really help your use case at all!

**Comment by westnordost** [comment]
Thanks for checking the other SDKs!

So for my use case, where would the pointer arrow point at if the result is not clipped?

**Comment by karimnaaji** [comment]
Maybe making lngLatToScreenPosition return the actual screen position if it lies within the screen (if unclipped), and a screen edge position otherwise? They could be classified internally and mapped to NDC cube faces before going it back to screen, z < -1: behind, z > +1: front, x < -1: left, x > +1: right etc.. That would cover the immediate use case of https://github.com/westnordost/StreetComplete/issues/1842.

**Comment by matteblair** [comment]
I like that idea - I'll try adding a version of this method that clamps to the NDC cube and reports whether clamping occurred. We can keep the previous behavior around since it's useful in other situations.

**Comment by matteblair** [comment]
Turns out that just clamping the projected point isn't a solution because the transformation to clip space is what causes the sign-flip behavior - when the point is in clip space it's already in the wrong direction. But I realized that even in these cases where we can't sensibly transform a _point_ into screen space, we can always transform a _direction_ into screen space. Knowing the relative direction is enough to indicate an off-screen point, as in this use case. This could also be used internally to clamp the results of lngLatToScreenPosition to the screen boundary. So now I'm considering two options:
 1. New method `lngLatToScreenPositionClamped` that returns a point on the edge of the screen if the point is off-screen.
 2. New method `lngLatToScreenDirection` that returns the screen-space direction of the point from the view center, for more general calculations.

**Comment by matteblair** [comment]
Thanks for the sample code @karimnaaji, this makes it a lot more clear. I've found from more testing that the condition that originally prompted this issue coincides with the `assert(false)` in this sample, so we'd need to figure out the right thing to do there.

I also realized that is more than one way to think about "clamping" for this use case:
![clampedvclipped](https://user-images.githubusercontent.com/3371850/84621435-878b1800-aea8-11ea-9540-66e517aa596b.png)
I've made some arbitrary naming choices here for the sake of discussion. "Clamping" gives you the screen point that is _closest_ to where the original point would be projected, whereas "clipping" give you the screen point that is _furthest_ in the direction towards the original point. The solution that I had been working on takes the "clipping" approach:
```cpp
glm::vec2 worldToScreenSpaceClamped(const glm::mat4& mvp, const glm::vec4& worldPosition, const glm::vec4& worldScreenOrigin, const glm::vec2& screenSize, bool& clamped) {
    glm::vec4 clip = worldToClipSpace(mvp, worldPosition);
    glm::vec3 ndc = glm::vec3(clip) / clip.w;

    if (abs(ndc.x) <= 1 && abs(ndc.y) <= 1 && abs(ndc.z) <= 1) {
        clamped = false;
    } else {
        clamped = true;
        glm::vec4 worldDirection = worldPosition - worldScreenOrigin;
        glm::vec4 clipDirection = worldToClipSpace(mvp, worldDirection);
        ndc = glm::vec3(clipDirection) / glm::max(abs(clipDirection.x), abs(clipDirection.y));
    }

    glm::vec2 screenPosition = glm::vec2(1 + ndc.x, 1 - ndc.y) * screenSize * 0.5f;
    return screenPosition;
}
```
The "clipping" result is not always as obvious as the "clamping" result, but for the use case of placing an indicator for an off-screen point, this seems like a good fit. This method also continues to work when the original point is on the wrong side of the camera plane, which is nice!

**Comment by karimnaaji** [comment]
Nice diagram! This makes a lot of sense to use the clipping method as it gives more details around corners. Clamping would fall through in the corner a lot more.

**Comment by westnordost** [comment]
Ah, this is fixed now! Thank you very much, I stopped following the discussion halfway because it seemed too complex to me, so thank you even more to having put that much effort into a solution!
