### ISSUE TITLE
bottom view no rotate 

### ISSUE THREAD

**Issue by ccxxbb** [tangrams/tangram-es#2171]
- steps：there is  top map  view and bottom map view in activity
 - result：no rotate  in bottom map view
 - envi  :  android   tangram-es-0.10.1

 - bug:    there is a bug in TwoFingerGestureDetector::getRawY  ,  offset  should be  float offset = event.getRawY() - event.getY() ,then work fine

**Comment by matteblair** [comment]
Thanks for the report! I've reproduced this behavior in a sample app with two map views stacked vertically in a LinearLayout. Just as you said, rotate gestures are detected in the top view, but not the bottom view.

I was very skeptical that this very old gesture code would have such a simple bug, since we have used it so long without problems. But it is definitely a bug! In fact, it has also been reported in the source repository for this library https://github.com/Almeros/android-gesture-detectors/issues/30

I'll fix this in a PR shortly.
