### ISSUE TITLE
New version of Tangram-ES

### ISSUE THREAD

**Issue by rwrx** [tangrams/tangram-es#2226]
I just wanted to ask you when are you planning to release new version of Tangram-ES. If you do not plan to release it in near the future, won't you release at least minor version 0.13.1? I am just asking. Thank you.

**Comment by matteblair** [comment]
Yes, I realize it has been a while since the last release. I am currently trying to resolve https://github.com/tangrams/tangram-es/issues/2218 before releasing a new version so that Android users don't have to risk crashes in their app if they upgrade.

However, since it is taking a while to track down the cause of that issue I could instead release a new version with a warning about this known issue. It is not ideal, but may be a sensible compromise.

**Comment by matteblair** [comment]
🎉  https://github.com/tangrams/tangram-es/releases/tag/0.14.0
