### ISSUE TITLE
Release 0.15.0 should be published to Maven Central

### ISSUE THREAD

**Issue by westnordost** [tangrams/tangram-es#2248]
I am confused by the v0.16. Is it the same as v0.15? In particular: Why did you not release v0.15 on jCenter **and** maven central?

This would be important because there are security considerations for this, as explained here: https://blog.gradle.org/jcenter-shutdown

> As we have seen in recent years, dependency confusion and namespace collisions can be serious dangers for supply chain attacks. Each of these vulnerabilities relied on untrusted artifacts being used in place of trusted ones.

The scenario would be this: Someone has the v0.15 as dependency, then, jCenter is shut down, so that someone changes his gradle config to target another repository. You did not upload v0.15 to maven central, but maybe someone else did, a modified binary with malicious code. To guard against this, gradle has a feature to check the signatures of the binaries. If the signature of one and the same library is the same, then the app will not build and report an error.

However, if v0.15 is only on jCenter and v0.16 is only on maven central, it is not possible to use this.

**Solution**: Upload v0.15 to both jCenter and Maven Central.

**Comment by matteblair** [comment]
The only difference between 0.16.0 and 0.15.0 is the release publishing process. Since the publishing process is part of the repository source, I wanted to make it distinct from the source that was tagged 0.15.0.

I can see how the repository change creates opportunities for namespace collision attacks in general, however the `com.mapzen.tangram` package on Maven Central has been registered for 4 years with user credentials belonging to only the Tangram ES maintainers. If an attacker was able to upload a malicious package for `com.mapzen.tangram:tangram:0.15.0` then I believe that would imply they could upload malicious packages for any version - but let me know if I'm misunderstanding.

That said! I can see the wisdom in publishing 0.15.0 to Maven Central as a convenience / safety measure. I'll see if I can do that manually.

**Comment by westnordost** [comment]
> package on Maven Central has been registered for 4 years with user credentials belonging to only the Tangram ES maintainers

Right, okay. Then I think this is all safe. Feel free to close it.
