### ISSUE TITLE
Cannot specify relative order of features drawn with 'overlay' blending

### ISSUE THREAD

**Issue by blair1618** [tangrams/tangram-es#405]

**Comment by bcamper** [comment]
FYI I had an old test branch in JS that allowed the order of entire styles to be controlled (with a `blend_order`):

https://github.com/tangrams/tangram/compare/blend-order

This is different from the desire for per-feature ordering of course, and has some downside in terms of potential semantic confusion, but could be considered as a relatively easy addition to the current architecture.

To allow per-feature ordering, my assumption is that we would have to do something like:

- Sort all features with blending in a tile by order.
- Sub-sort by style, so that we consolidate as many continuous groups of features by style as possible (the features in the group don't all need to have the same order, the orders just need to be ascending without changing styles).
- For each style, continue to put all blend features in the same VBO as the opaque geometry, but maybe contiguously at the end of the buffer (after the opaque features)?
- For each group, store a VBO offset range or separate element buffer.
- When rendering, have additional draw calls for each group, switching to the appropriate style/VBO for each, and rendering the subset of features.

Issues:

- Could potentially add a lot of draw calls, but maybe not under "normal" circumstances? e.g. probably fine for hand-written rules, but could be an issue for a dynamic `order` that had many distinct values interweaved across styles (possibly rare).
- Could still have rendering issues across tiles?

**Comment by blair1618** [comment]
Yeah, I think for our needs in eraser-map it will be sufficient just to specify the relative order of entire styles. An example problem we're trying to solve: the icon drawn at your current position while routing is placed *under* the actual route line. This class of issues can be fixed with per-style order. 

In summary, one approach looks like:

 - Add `blend_order` or analogous parameter for styles, applying only to styles that use blending
 - Sort styles as we currently do to put blended styles above opaque styles
 - Within that style list, sort blended styles by `blend_order`
 - Draw as usual, letting painters-algorithm-drawing of blended styles take care of ordering
 - ????
 - Profit

**Comment by tallytalwar** [comment]
@blair1618, What you described make sense for style ordering and should solve the case you mentioned above (which is route icon to be drawn above route line). 
This should also solve the case of routing icon drawn above search results, where route_icon and search results have different styles (and hence blend orders) assigned.

But this won't solve blending of features drawn with the same style (eg. multiple search results overlapping each other). What @bcamper described could solve this also, but also involves a complicated change in the pipeline.

**Comment by bcamper** [comment]
OK. It's not perfect but it gets the job done.

Is `blend_order` the right term? Just plain `order` would work, though I think I was worried about confusion by overloading that term for style vs. draw definitions. `style_order`? `overlay_order` (clashes with `inlay`)?

Does this apply to `add` and `multiply` blend modes? In my previous branch, it only applies to `overlay` and `inlay`, but I'm not sure that is right (seems you'd want to use this feature to put something like a route on top of other features, even if they had transparency). Further, I was still drawing all `inlay` styles, then all `overlay` styles after. It seems the correct approach would be to instead group all non-opaque blend styles (`overlay`, `inlay`, `add`, `multiply`) by `blend_order`, which might mean additional state switches (changing blend modes back and forth), but we can set default orders that avoid this (and this kind of style ordering seems rather advanced anyway).

I'm still not entirely satisfied by this approach since it feels quite coupled to our rendering pipeline and involves multiple concepts of "order", but it may be the best option in the short-term. What do we think happens to something like this longer term? Is it eventually deprecated/replaced by a per-feature order?

**Comment by blair1618** [comment]
In the long-term I'd like to try a different approach to order altogether, probably using a rendering pre-pass for order (and whatever else is useful).

I think the practical move here would be to implement this per-style order now and deprecate it when it's no longer needed (since I think we all want something better down the road). 

The name should indicate that it only applies to styles with some kind of blending, so `blend_order` works for me.

**Comment by nvkelso** [comment]
> This should also solve the case of routing icon drawn above search results, where route_icon and search results have different styles (and hence blend orders) assigned.

How does this work today? Search results & route icon share the same style (`icons`), but have different declarations. How can the route icon be above all other artwork assets?

**Comment by blair1618** [comment]
> How does this work today?

It doesn't :) 

I don't believe either tangram implementation has a way to guarantee order among features in an "overlay" style.

**Comment by bcamper** [comment]
Right, it may coincidentally be drawing the way you want it, but that could
change unpredictably.

**Comment by tallytalwar** [comment]
Both tangram and tangram-es support `blend_order` now to order features drawn with non-opaque styles.

JS: https://github.com/tangrams/tangram/pull/223
ES: https://github.com/tangrams/tangram-es/pull/438

Marking this resolved.
