### ISSUE TITLE
"make clean" shouldn't download things it doesn't need to

### ISSUE THREAD

**Issue by msmollin** [tangrams/tangram-es#447]
If you run make clean, it will go through the hoops of downloading and installing gradle and a bunch of apache projects in an attempt to clean a nonexistent android build (in my case, I had run `make xcode`). See attached screenshot.

![screen shot 2015-12-23 at 11 52 40 am](https://cloud.githubusercontent.com/assets/1163880/11980830/b67bfc7a-a96b-11e5-9b3c-9a7ed34f88a6.png)

**Comment by tallytalwar** [comment]
Ahaa... so `make clean` is a uber clean. If you have had done `make android`, `make osx`, `make xcode`, etc... `make clean` takes care of all.

For `xcode` you can do `make clean-xcode`.

**Comment by msmollin** [comment]
I see. Is there a reason for it? Other than it's expected of projects using the CMake build system to have a "clean" step? Just seems like the amount of side-effects involved with the clean step is out of line with what clean is supposed to do, i.e. remove files and dependencies - not install new & unnecessary ones?

**Comment by msmollin** [comment]
Specifically with gradle, installing a new, very old gradle build chain (latest version is 2.10 - this is installing 2.2.1) has the distinct possibility of breaking any existing gradle configurations. Making an assumption that ~/.gradle/ is unused and available to be overwritten is a Bad Idea™ (regardless of whether or not the installer will actually do that).

**Comment by tallytalwar** [comment]
Hmm.. for all other targets, clean just does a `rm -rf` on the respective build directory.

But for `android`, it also runs a `gradlew clean` which takes care of cleaning the android project.

**Comment by tallytalwar** [comment]
Ohh, didn't know its installing an old version, I am not sure where thats happening, if you refer the makefile, it only does a `./gradlew clean`. [here](https://github.com/tangrams/tangram-es/blob/master/Makefile#L154-L158)

**Comment by msmollin** [comment]
That's about where my knowledge of gradle ends :) No idea why it would attempt an install then. I would just expect that command to fail. @ecgreb may have a better idea. But yeah, 2.2.1 is from November of 2014.

**Comment by tallytalwar** [comment]
Probably this is the reason: https://docs.gradle.org/current/userguide/gradle_wrapper.html.

**Comment by tallytalwar** [comment]
Based on the gradle wrapper documentation, probably we should update our `build.gradle`, with:

```
task wrapper(type: Wrapper) {
    gradleVersion = '2.0'
}
```

**Comment by blair1618** [comment]
This may be more of a documentation issue. What's not clear from the build instructions that the default `make` tasks are for *all build targets*. This is slightly unusual if you aren't accustomed to cross-platform projects. As Varun pointed out, the tasks that you want to use when targeting Xcode for OS X would be `make xcode` and `make clean-xcode` (iOS would be `make ios` and `make clean-ios`, etc.). I'm not opposed to reconsidering the default semantics of `clean`, I just can't think of a better solution for developing for multiple targets simultaneously. 

The `clean-x` tasks don't have any unnecessary side-effects. `clean-ios`, for instance will just `rm -rf` the ios build folder. The Android project uses Gradle for the Java build steps, so to properly clean those build files we need to run `gradle clean`, and this in turn requires that a suitable Gradle version is installed. Running `make clean` cleans all the build targets, including Android, so this will initiate a Gradle install if you don't have the correct version. 

Gradle installs distributions to `~/.gradle/` in a sub-folder specific to each version, so nothing will be overridden even if another version is installed (this behavior is Gradle's choice, not ours). For reproducibility, Gradle recommends that projects be pinned to a specific version of Gradle and thus require that specific version of Gradle to be installed (via the Wrapper that Varun mentioned). We haven't specified a newer version of Gradle because we have no issues with the current version, but if you'd like to suggest upgrading then feel free to make an issue for that.

**Comment by blair1618** [comment]
@msmollin would https://github.com/tangrams/tangram-es/pull/450 make this less confusing?

**Comment by nvkelso** [comment]
Seems weird that 'make clean' would be a dry run only.

**Comment by bcamper** [comment]
I believe idiomatic 'clean' target is to cleanup the environment, not
necessarily to build artifacts, e.g.
https://www.gnu.org/software/make/manual/html_node/Cleanup.html

**Comment by nvkelso** [comment]
Just you:

But shouldn't it **clean** by removing files, not listing files to remove?

**Comment by bcamper** [comment]
Sounds right :)

**Comment by msmollin** [comment]
Catching up here. Couple thoughts around the PR @blair1618 put in:

I think I'm OK with `make clean` being a no-op and listing additional required targets if that's what `make` already does, and is easiest to implement. 

However I think a better way in the long term to approach it is to attempt to use whatever gradle is available on the local system, similar to how you use whatever xcodebuild is available in the system, and just fail to build otherwise. 

I believe that's part of the reason that generally before running make you run through a configuration step that produces a configuration file with the necessary paths and such to the required components needed for building. It is, at that stage, you would require the end user to provide a path to gradle if they wanted to build / clean android.

Thats just my $0.02 tho. Your no-op route I think is fine assuming no one else closer to the project has an issue with it.

**Comment by blair1618** [comment]
https://github.com/tangrams/tangram-es/pull/452 might be more amenable to all parties. 

@msmollin re: using whatever gradle is available or asking the user for a gradle path -

I see where you're coming from on this, but these approaches would be contrary to paradigmatic Gradle usage. As explained in the documentation on the [Gradle Wrapper](https://docs.gradle.org/current/userguide/gradle_wrapper.html), letting the build system ensure that the correct tools are installed at the correct versions creates a much easier experience for the end-users *and* for the developers. 

Using the example of `xcodebuild` that you mentioned, I've had at least one occasion where I've been unable to build a project because I had a different version of Xcode than the project developer. Gradle's tactic here is simply to download the version that the project is pinned to. This makes sense for Gradle, but not for multi-gigabyte packages like Xcode. 

Regardless, with the latest PR you can pretend that Gradle doesn't exist unless you are explicitly targeting Android :)

**Comment by blair1618** [comment]
Resolved: https://github.com/tangrams/tangram-es/pull/452
