### ISSUE TITLE
Full font texture atlas size reached error

### ISSUE THREAD

**Issue by softlxf** [tangrams/tangram-es#516]
### When I use Chinese font, my poi data which has a large number of Chinese characters would fill font texture atlas to full, then error occurred.

here is my log:
01-30 12:07:43.302 702-836/com.mapzen.tangram.android D/Tangram: WARNING fontContext.cpp:195: Texture Atlas resized to 1024 1024
01-30 12:07:43.769 702-836/com.mapzen.tangram.android D/Tangram: WARNING fontContext.cpp:195: Texture Atlas resized to 2048 2048
01-30 12:07:45.972 702-772/com.mapzen.tangram.android D/Tangram: ERROR fontContext.cpp:189: Full font texture atlas size reached!
...
01-30 12:07:46.368 702-772/com.mapzen.tangram.android D/Tangram: ERROR fontContext.cpp:189: Full font texture atlas size reached!
01-30 12:07:46.368 702-772/? D/Tangram: ERROR fontContext.cpp:189: Full font texture atlas size reached!
01-30 12:07:46.368 702-772/? D/Tangram: ERROR fontContext.cpp:189: Full font texture atlas size reached!

**Comment by czxczq521** [comment]
I am also concerned about this issue

**Comment by czxczq521** [comment]
If try to change TANGRAM_MAX_TEXTURE_WIDTH and TANGRAM_MAX_TEXTURE_HEIGHT size to 4096, that is OK？

**Comment by karimnaaji** [comment]
We currently do not support atlas regeneration nor multiple-atlases, but we will add some mechanism around that. The limitation on `TANGRAM_MAX_TEXTURE_WIDTH/HEIGHT` of 2048 is a device-hardware compatibility/limitation, since most of mobile devices support this size as the maximum texture size; but it would make sense to make this size a per-hardware value.
