### ISSUE TITLE
Handle arbitrary layers from a client geojson datasource

### ISSUE THREAD

**Issue by tallytalwar** [tangrams/tangram-es#535]
Currently tangram-es core architecture requires datasource to contain features in appropriate uber layers, which are then be styled/filtered upon. However it is totally fine for a geojson to provide a feature collection with no uber layer defined (eg: https://transit.land/api/v1/operators.geojson).

Tangram-es should provide a way for these feature sets to be filtered/styled and drawn.

**Comment by bcamper** [comment]
Almost all GeoJSON sources will be a standard FeatureCollection. The presence of a JSON wrapper splitting these into "layers" is just an arbitrary format that Tangram implemented. In Tangram JS we're supporting both -- a single GeoJSON object, or a set of layers provided as GeoJSON objects -- for both tiled and non-tiled GeoJSON (it was initially implemented for tiled GeoJSON since that's how our tiles were formatted, and then carried over to non-tiled GeoJSON because the code is shared).

**Comment by bcamper** [comment]
For styling/filtering purposes, single-layer data sources simply omit the `layer` property in the `data` block, e.g.:

`data: { source: geojson }` is used to reference the data
