### ISSUE TITLE
Polyline "outline" parameters should be able to override "style" of enclosing rule

### ISSUE THREAD

**Issue by blair1618** [tangrams/tangram-es#544]
https://github.com/tangrams/tangram-docs/blob/gh-pages/pages/draw.md#outline (an outline will respect *any* parameters that a line style will, including "style")

This is a bit tricky with the way we've implemented outlines in ES. I think for outlines that specify a different style than their enclosing rule, we'll have to generate a new draw rule for the outline that uses the outline's style, making sure that the outline still has the correct order offset from the original line rule.

**Comment by bcamper** [comment]
That is close to what the JS implementation does: it synthesizes a set of
`draw` parameters as if the outline were a regular line (including setting
appropriate order) and calls the `addFeature` method on the outline's
style. It's led to a couple gotchas, especially around
preprocessing/caching steps, since those are the only draw groups that
don't exist in full in the scene file, but it is still likely the most
expedient way.

**Comment by tallytalwar** [comment]
I did start something on the lines of js implementation for this. Couldn't
think of anything different :!.
