### ISSUE TITLE
Building rendered repeatedly if the building exists in more than one tile

### ISSUE THREAD

**Issue by softlxf** [tangrams/tangram-es#545]
When I set buildings translucent(blend overlay), some building exists in more than on tile look relatively deep color!

**Comment by nvkelso** [comment]
Thanks for the report @softlxf! Can you include a screenshot please, perhaps also with a scene file snippet?

**Comment by nvkelso** [comment]
@bcamper Another reason to support clipped vector tiles? Or can you solve this on the Tangram side?

**Comment by bcamper** [comment]
Right, this would be fixed if we clipped all buildings to the tile edges. The main reason we haven't done that so far is to allow proper UV calculation across the building (and other potential rendering artifacts). If the building is split across tiles, the UVs, as currently calculated based on the polygon's AABB, would not line up where tiles meet.

There have been proposals to clip to tile and to include hints that the client could use to calculate those UVs, but that raises the barrier to usefulness in other clients besides Tangram.

Another solution would be leave buildings un-clipped, but ensure they don't repeat across tiles. This is difficult with OSM data because there is often no actual "building" concept (where the relations are not set properly, it's just a series of overlapping boxes that happen to look like a building when rendered together). We could only include each component box in the tile of its centroid, which would cause strange rendering if some but not all tiles were loaded, but that also should not occur in normal view situations.

@nvkelso: also note that this rendering overlap issue would always exist with buffered MVT tiles (unless there were some further special handling like clipping buildings to the "true" tile edge while clipping lines to the buffer... gets messy).

cc @blair1618 also

**Comment by blair1618** [comment]
For 2D geometry a neat solution is for the renderer to draw every tile using a stencil of its boundaries - this is what the mapbox renderer does if I recall - but this becomes impractical once you add geometry that extends out of the xy plane.

**Comment by softlxf** [comment]
@nvkelso @bcamper: We expect the building repeat across tiles just rendering one time; when building in tile A rendered, the repeated building in tile B would be ignored, do not render; 
~ repeat building have the same building id.

![screenshot](https://cloud.githubusercontent.com/assets/7391156/13135609/40baaba8-d64d-11e5-84fc-2bf76120abf2.png)

**Comment by bcamper** [comment]
@softlxf Makes sense, see my comment above. This is something we will be addressing in the future, likely by changing the underlying tile data (either clipping buildings at tile edges, or ensuring each building piece is only included in one tile). In the meantime this is a rendering limitation, but we will keep this issue open, or create a new issue to reflect the solution.

Thanks for your feedback! May we ask for any information about the application you are developing? It's helpful to for us understand the real-world use cases to guide our development. Please fee free to contact me privately at brett@mapzen.com as well if you prefer.

**Comment by matteblair** [comment]
This use case is covered by the `blend: translucent` option now. Closing!
