### ISSUE TITLE
Should to add the point icon may support the direction of icon

### ISSUE THREAD

**Issue by czxczq521** [tangrams/tangram-es#551]
I add the point icon in map, the icon should support direction,but don't find interface to support, how to support gps location icon and it's direction.

![image](https://cloud.githubusercontent.com/assets/16661939/13099453/496a860a-d56d-11e5-942e-1bb53b3c2426.png)

**Comment by blair1618** [comment]
tangram-es doesn't have a way to set the rotation of point geometries right now, but a new approach for managing simple point geometries like this is coming soon!

**Comment by bcamper** [comment]
Actually, Tangram JS does support `angle` (in degrees) on a `point` style geometry, but this is apparently [undocumented](https://github.com/tangrams/tangram/blob/063e72e093771c1d8b45a9b13bd2680f7d9febcd/src/styles/points/points.js#L144) (it is primarily used for internal rotation of labels).

It looks like this may be partially but not fully implemented in ES?

It's in the [vertex layout](https://github.com/tangrams/tangram-es/blob/master/core/src/style/pointStyle.cpp#L36) and [shader](https://github.com/tangrams/tangram-es/blob/master/core/resources/shaders/point.vs#L81)

But `angle` is [not parsed](https://github.com/tangrams/tangram-es/blob/master/core/src/style/pointStyle.cpp#L133-L144) as a `draw` parameter.

@karimnaaji does that sound right or did I miss something?

We should decide either complete support in ES and add to docs, or disable the parsing in JS.

**Comment by nvkelso** [comment]
+1 for supporting this across both platforms, please don't remove it! 

There is data in OSM for viewpoints that includes angle and we could immediately use this feature in our house map styles. It's also interesting to think about for things like tunnel and bridge icons which should be angled along the road.

**Comment by bcamper** [comment]
FWIW angling along a road would be computed dynamically, similar to
labels... but the use cases for peaks based on tile data is interesting.

**Comment by meetar** [comment]
Also for things like vector fields! ➚

**Comment by blair1618** [comment]
Tangram-es *could* parse an 'angle' draw parameter and interpret it the way that tangram-js does for point style geometries, but the meaning of 'angle' becomes more complicated when the map view can change orientation, as in tangram-es. 

In some cases you may want to rotate a geometry in *screen space*, like a tilted billboard. This is the current behavior of the 'angle' draw parameter in tangram-js and the internal angle attribute in tangram-es. 

However, in other case you'll want to rotate a geometry in *world space*, that is, specify its orientation relative to the cardinal directions (this is the case for a routing icon, an oriented location gem, icons that align with roads, etc.). Because tangram-js does not allow view rotation, screen-space angles and world-space angles happen to be the same. In tangram-es the view can rotate and tilt, so setting a screen-space angle would result in very different behavior from setting a world-space angle. 

Since 'angle' is ambiguous about the coordinate system it refers to, I think it would be better in the long run to develop a way of specifying either a screen-space orientation or a world-space orientation and to make those parameters more clear in syntax.
