### ISSUE TITLE
Search-active and search-inactive icons are corrupted and upside down

### ISSUE THREAD

**Issue by sensescape** [tangrams/tangram-es#567]
Now, upon tapping on an icon
![screenshot_2016-02-24-11-12-54](https://cloud.githubusercontent.com/assets/466585/13298088/38b5f876-daea-11e5-8cb2-4657d75f4e63.png)

or search results:
![screenshot_2016-02-24-11-25-35](https://cloud.githubusercontent.com/assets/466585/13298104/49b05fc2-daea-11e5-8ed0-3f3d1455fe55.png)

previously looked like this:
![screenshot_2016-02-24-11-25-38](https://cloud.githubusercontent.com/assets/466585/13298123/57869832-daea-11e5-98ff-5561e31f30f0.png)

**Comment by nvkelso** [comment]
This started in master-980 when we updated the sprite sheet. But looking at the definition, the region is correctly set in the scene file (`search-active`, `search-inactive`). 

Is this related to sprite sheet optimization work that happened recently in Tangram ES?

**Comment by nvkelso** [comment]
Specifically: https://github.com/tangrams/eraser-map/commit/4665596453694cd7998ce3715b814b6d6e55a010#diff-939bb555547386cbe68c2ce87237df85R322

**Comment by blair1618** [comment]
Looking at the sprite definition [here](https://github.com/tangrams/eraser-map/blob/gh-pages/eraser-map.yaml#L322), and the sprite sheet [here](https://github.com/tangrams/eraser-map/blob/gh-pages/images/poi_icons_18%402x.png), it looks like the sprite definition goes beyond the edge of the image ( 342px + 108px > 446px). We don't really define the behavior in this case, and it may be a good idea for us to catch those sorts of accidents in tangram-es, but the problem can be fixed by changing the sprite definition.

**Comment by nvkelso** [comment]
Sounds like a bug in my export script :\ I'm surprised it never surfaced before, though!

Verifying the change now, then will close this issue.

**Comment by nvkelso** [comment]
Verified.
