### ISSUE TITLE
SceneLoader: allow to use globally defined textures in materials 

### ISSUE THREAD

**Issue by hjanetzek** [tangrams/tangram-es#594]
Probably a bug, haven't tested but there seems to be no code to handle this case. Also all textures should be added to scene.textures so that equal instances can be shared

**Comment by blair1618** [comment]
If I understand the issue, I think the code that's meant to handle it is: 

https://github.com/tangrams/tangram-es/blob/master/core/src/scene/sceneLoader.cpp#L319-L322

But it wouldn't hurt to confirm that this works. 

We don't add *all* textures to `scene.textures` right now because textures that are defined "inline" for styles or materials aren't given a name and can't be legally accessed by any other part of the scene file.

**Comment by tallytalwar** [comment]
Looks like `SceneLoader:: loadMaterialTexture` does have code for this.

**Comment by tallytalwar** [comment]
Closing this, as per the discussion above we do have code to support this.
