### ISSUE TITLE
failed: dlopen failed: cannot locate symbol "_ZN7Tangram11setPositionEdd" referenced by "libtangram.so"...

### ISSUE THREAD

**Issue by nomizodiac** [tangrams/tangram-es#608]

**Comment by blair1618** [comment]
Hello! Thanks for submitting your issue. Can you tell me what operating system you're using, which target you're trying to build, and what steps you followed that led to this error? Thank you

**Comment by nomizodiac** [comment]
Basically i am trying to build and compile tangram-es to use it as library project for vector tiling in my project. Following are two steps that i have followed

*I have downloaded the tangram-es complete package (including 'core') and then open 'android' [project ](https://github.com/tangrams/tangram-es/tree/master/android) in android studio. Now this project compile and build successfully but give me exception when i run it which says "Exception Ljava/lang/UnsatisfiedLinkError; thrown while initializing Lcom/mapzen/tangram/MapController;" By googling i found that it does not generate .so files that we are loading from MapController.java class due to which it throws linking error.

*Then i switched to manual/other way compiling it. I added all source (cpp) files from core to jni folder inside the project and also added android.mk and application.mk files in it and did changes in build.gradle to build it manually. Changes and codes are mentioned in this [link](http://stackoverflow.com/questions/35741761/android-ndk-exception-failed-dlopen-failed-cannot-locate-symbol-zn7tangram11). When i build the project now it generates a jniLib folder and tangram.so, c++_shared.so files in it but when running it throw me above error.

Following are my platform details:
Windows 7 64-bit OS
Android Studio 1.5 
android-ndk-r10e
Building for APP_PLATFORM := android-19
Running on Huawei Honor 4C CHM-U01, 4.4.2 Kitkat
also tried to run on 
Samsung galaxy s5, 5.0 Lollipop by building for APP_PLATFORM := android-21

Apologies if i didn't get something right as i dont have much expertise in ndk/cpp stuff. Please guide me if above two approaches are right or else can you provide some other way or steps need to follow to compile/build this project? Thanks

**Comment by nomizodiac** [comment]
Can you please specify on which ndk version this code is compiled?

**Comment by tallytalwar** [comment]
Hi Nouman

Yup, because of the libTangram.so dependency you will not be able to build the demo application directly from android studio.
Also thanks for specifying your platform details, we do not have any official support for windows build for tangram yet! But, the following instructions might help you get an android build working on windows.

To run the demo application, we have a cmake toolchain for android, which is used to build the tangram library. To make this cmake toolchain run on windows you might have to modify the NDK build tools path to use **`windows-x86_64`** instead of **`darwin-x86_64`**, [here](https://github.com/tangrams/tangram-es/blob/12ddd826725171aa4a23516c6d7df0cd63060b59/Makefile#L112). You might be able to explicitly call cmake instructions as specified in the [makefile](https://github.com/tangrams/tangram-es/blob/master/Makefile) to get the library compiled for android use.

Sorry, we do not have any official support for windows build (including android builds on windows), hence the above manual process.

**Comment by tallytalwar** [comment]
We also have tangram library snapshots in maven, you can grab it for your application by setting the following in your `build.gradle`:

```
dependencies {
    compile 'com.mapzen.tangram:tangram:0.1-SNAPSHOT'
}
```

This is a snapshot which is updated with every push to our master branch, so could have breaking API changes. We do plan to have proper Maven Central releases for tangram which will be more stable and versioned.

Hope this helps.

**Comment by blair1618** [comment]
Rather than directly compiling tangram-es with the NDK, android applications should now use the tangram dependency available on Maven central ([here](http://search.maven.org/#search|ga|1|tangram)).
