### ISSUE TITLE
label `skipTransition` seems to be broken with latest tangram build

### ISSUE THREAD

**Issue by tallytalwar** [tangrams/tangram-es#638]
Skipping transition for labels going from one zoom level to another on a labelHash match seems to be not working with the latest tangram (post alfons merge). Requires investigation and a fix.

**Comment by hjanetzek** [comment]
It works just as good as before here. Though it can certainly be improved. 

I think the main problem is that labelHash is too restrictive when the text-style of a feature changes between zoom-levels or has a dynamic attribute depending on zoom. For this case one would need a style-group-id + labelText to match on so that transitions can be skipped for a label of the same feature even when the used style has changed (which happens on nearly every zoom for eraser-map).

**Comment by blair1618** [comment]
Update? Is this actually a bug?

**Comment by blair1618** [comment]
Haven't heard of this being reproduced; closing.
