### ISSUE TITLE
harfbuzz Cmake error

### ISSUE THREAD

**Issue by ric96** [tangrams/tangram-es#660]
pi@raspberrypi:~/tangram-es $ make -j4 rpi
-- Platform chosen : RASPBERRYPI
-- Including raspberrypi dependent cmake file : /home/pi/tangram-es/toolchains/raspberrypi.cmake
-- Looking for GLM
-- GLM include /home/pi/tangram-es/core/include/glm
CMake Error at external/alfons/deps/CMakeLists.txt:6 (add_subdirectory):
  The source directory

    /home/pi/tangram-es/external/alfons/deps/harfbuzz-icu-freetype

  does not contain a CMakeLists.txt file.

-- harfbuzz
-- Configuring incomplete, errors occurred!
See also "/home/pi/tangram-es/build/rpi/CMakeFiles/CMakeOutput.log".
Makefile:256: recipe for target 'cmake-rpi' failed
make: *** [cmake-rpi] Error 1
pi@raspberrypi:~/tangram-es $ 

PS: this happens even on linux builds

**Comment by blair1618** [comment]
This probably means that your git submodules are not up-to-date. When checking out the repository or pulling upstream changes, you should run 
```
git submodule update --init --recursive
```
to ensure that your submodules have the latest changes (as the README describes). 

If that doesn't work, it could be because the URL of a submodule has changed. In that case, try
```
git submodule sync --recursive
```
(you may then need to run the first command again). 

Give that a try and let me know if your issue is fixed.

**Comment by ric96** [comment]
i used to use this command which worked well
git submodule init && git submodule update

but now it seems that 
git submodule update --init --recursive
works, thanks!

**Comment by tallytalwar** [comment]
Yup, we have recursive submodule dependencies now.

Thanks for confirming the fix. Will close this issue.
