### ISSUE TITLE
Label showed behind the polygon with extrude setting.

### ISSUE THREAD

**Issue by ilully0802** [tangrams/tangram-es#719]
Hi, are there some ways to hide the label behind polygon with extrude? Now all the labels are shown whether the label is front of or behind the polygons, this sometime makes confuse.

**Comment by karimnaaji** [comment]
Hi @ilully0802 , 
This feature could be achieved by using the `inlay` blend mode https://mapzen.com/documentation/tangram/styles/#blend. Unfortunately, only the [javascript](https://github.com/tangrams/tangram) version of Tangram does support this feature for now, you can follow this issue here https://github.com/tangrams/tangram-es/issues/595.

**Comment by ilully0802** [comment]
Hi karimnaaji , thanks your cue, #402  has mentioned some resources with branch 'inlay-stencil', but this branch can not be found in github now, how can I follow this branch? Thanks!

**Comment by karimnaaji** [comment]
This branch was deleted but I restored it, you can find it here https://github.com/tangrams/tangram-es/tree/inlay-stencil.

**Comment by ilully0802** [comment]
Thanks karimnaaji.

**Comment by tallytalwar** [comment]
Closing in favor of https://github.com/tangrams/tangram-es/issues/595
