### ISSUE TITLE
Destroy MapController instance on MapView destroy

### ISSUE THREAD

**Issue by tallytalwar** [tangrams/tangram-es#729]
Currently we only clear the async tasks on MapView::onDestroy.
But if one creates a new activity, it grabs the old/previously initialized MapController instance.

Maybe it makes sense to destroy the mapController instance on a MapView::onDestroy.

**Comment by ecgreb** [comment]
Upon further thought there are times we do indeed want `MapController` to persist when `MapView` and its parent `Activity` are destroyed. For example on device rotation. Maybe instead of automatically destroying the `MapController` in `MapView#onDestroy()` we should add a public method like `MapView#resetMapController()`?

Also as @sarahlensing pointed out currently [`MapView#getMapAsyc(OnMapReadyCallback, String)`](https://github.com/tangrams/tangram-es/blob/master/android/tangram/src/com/mapzen/tangram/MapView.java#L54) ignores the `sceneFilePath` param if there is a `MapController` already in existence. It should probably at least call [`MapController#loadSceneFile(String)`](https://github.com/tangrams/tangram-es/blob/master/android/tangram/src/com/mapzen/tangram/MapController.java#L182) if the scene files are not the same.

**Comment by blair1618** [comment]
It sounds like the practical problem here is that re-initializing a tangram instance with a different scene file doesn't actually load the new scene. This wasn't an intentional design choice and can be easily remedied. I'll submit a PR today.
