### ISSUE TITLE
how can i use it on android on windows7

### ISSUE THREAD

**Issue by TGISer** [tangrams/tangram-es#746]
how can i get the Android.mk file and compile the core into .so   and  then run the android demo

**Comment by tallytalwar** [comment]
Hey

We have not streamlined building tangram-es for windows (both for android and windows itself) yet. However you can refer to some discussions (here)[https://github.com/tangrams/tangram-es/issues/401] of possible approach/solution.

We do plan to get to windows builds but there is no time frame as of now.

Thanks

**Comment by TGISer** [comment]
@tallytalwar   thank you  and  how can i get android.mk file  i very need it thank you !

**Comment by TGISer** [comment]
@tallytalwar   i want use ndk and Android.mk file to compile the core to .so file   how can i get the android.mk file

**Comment by hjanetzek** [comment]
@TGISer you can use the Mapzen SDK for Android unless you want to develop the Tangram library
https://github.com/mapzen/android

**Comment by TGISer** [comment]
@hjanetzek   thank you .  but i want to develop the Tangram library . and i want get the Android.mk file.
can you give me some hlep thank you !

**Comment by tallytalwar** [comment]
A welcomed initiative to help us grow the tangram library more. Thank You!

We do not use android.mk (directly) but have a cmake toolchain to take care of out android builds for tangram. As I mentioned before, you can refer to #401 for some pointers/tips on how you can modify the toolchain files to make android builds work for windows.

Also since we do not have any windows setup for tangram development as of now, and if you want to contribute to our project I would suggest using a linux distribution like Ubuntu, etc to help in Tangram development.

If you only want to extend tangram-es android project you can also get latest tangram-0.2.2 release from maven central [here](http://search.maven.org/#search%7Cga%7C1%7Ctangram), and include/extend its functionality in your own android application. Some documentation and example of which can be found in out documentation:

* Walkthrough: https://mapzen.com/documentation/tangram/android-walkthrough/
* APIs: https://mapzen.com/documentation/tangram/android-sdk/0.2.1/
* Examples: https://github.com/tangrams/tangram-android-demos

**Comment by TGISer** [comment]
@tallytalwar  thank you for reply and now i want build tangram-es for andorid on Ubuntu ,i set ANDROID_NDK and ANDROID_HOME  environment variable, and use "make android" but it can not right work ,where can i find the whole step to build tangram-es for android on Ubuntu.

**Comment by TGISer** [comment]
@tallytalwar  i build tangram-es for linux and run it ,but i can only see the font on it

**Comment by blair1618** [comment]
Hi @TGISer, can you check the console output and paste any errors or warnings you see? That would help us figure out what the problem might be.

You might also want to try a `git pull` and then `make` the project again because there was a fix added specifically for linux yesterday: https://github.com/tangrams/tangram-es/pull/759

**Comment by TGISer** [comment]
@blair1618   
Sorry i git pull again and rebuild it but the problem can not solve and i do not find the and errors or warning.

[100%] Building CXX object external/alfons/src/CMakeFiles/alfons_wrap.dir/alfons/lineWrap.cpp.o
Linking CXX static library ../../../lib/libalfons_wrap.a
make[3]: Leaving directory '/home/tgiser/桌面/tangram-es-0.3-android/build/linux'
[100%] Built target alfons_wrap
make[2]: Leaving directory '/home/tgiser/桌面/tangram-es-0.3-android/build/linux'
make[1]: Leaving directory '/home/tgiser/桌面/tangram-es-0.3-android/build/linux'
