### ISSUE TITLE
Proper way to add custom markers?

### ISSUE THREAD

**Issue by westnordost** [tangrams/tangram-es#763]
This is more of a question or perhaps a feature request if the answer is positive:

I have the use case that I want to display markers with custom icons on the map from an own data source (so, not directly OSM data or similar) as an overlay over the normal tangram map. I want to do _something_ when the marker is clicked.
Basically, I want to use pretty much the same functionality that is offered in the mapbox android API - [add a listener for click on marker](https://www.mapbox.com/help/android-markers/#marker-events) and [specify an own icon for a marker](https://www.mapbox.com/help/android-markers/#change-a-marker-icon)

**Now, did I understand it correctly that the way to achieve this in tangram-es is to:**

1. for any marker to be added, add some custom properties like i.e.` my_custom_icon=xyz`, `my_custom_action_id=abc` when calling `MapData::addPoint`
2. add a custom feature pick listener via `MapController::setFeaturePickListener`
3. in this custom feature pick listener, only do the _something_ when the custom properties are present (otherwise ignore). Switch through `my_custom_action_id` to decide which kind of thing to do
4. copy or better fork the tangram style of your choice and add it as a git submodule to your project, because the style.yaml has to be modified
5. define all the custom icons one needs in the forked style.yaml and edit the style.yaml in a way that if my_custom_icon is defined for a point, then this icon is used

If this is the (easiest) way, it is a bit of a show-stopper for me, mostly because of points 4-5. I.e. the bubble-wrap style has something over 6000 LOC and is growing continuously. I guess this goes for every definition file that specifies how the OSM data should be rendered, MapBox has the same problem of super-large CartoCSS files.
I know, this is another problem to be tackled one day, but by treating any overlay, even markers for the own location, for search results etc. as part of the styled map, the problem is passed on to creating overlays and custom markers.

But well, given of course that what I described above _is_ actually the way to define custom markers in tangram-es.

**Comment by westnordost** [comment]
I realize that I wrote the issue more in a way of a feature request than a question. But actually, I am more interested in an answer to whether I understood the procedure to achieve custom markers correctly than to start a discussion about this topic. Sorry if that did not come across.

**Comment by blair1618** [comment]
Hi @westnordost 

To answer your primary question: yes, that is currently the "right" way to achieve what you want in tangram-es. The engine has focused almost entirely on base map rendering so far, and because of that it's really awkward to do things like overlays and annotations right now. BUT I have two pieces of good news for you:

1. Working with large scene files is about to get much, much easier because of [scene imports](https://github.com/tangrams/tangram/pull/278). This will be available in the next release of tangram-es ([follow here](https://github.com/tangrams/tangram-es/pull/720))

2. [Proper marker support](https://github.com/tangrams/tangram-es/issues/653) is on the way. This will include revisions to touch/click callbacks as well. Expect this to land in 2 or 3 weeks.

**Comment by westnordost** [comment]
Oho! Thanks for the info! I'll close this issue as the question has been answered.
