### ISSUE TITLE
A BUG: can not find "cxxabi.h"

### ISSUE THREAD

**Issue by Oliver001** [tangrams/tangram-es#804]
There are maybe a mistake in file ./toolchains/android.toolchain.cmake at line 1039.
`set( ANDROID_ABI_INCLUDE_DIRS "${ANDROID_CXX_ROOT}/llvm-libc++abi/include" )`

and I find the correct dir of ANDROID_ABI_INCLUDE_DIRS is  "${ANDROID_CXX_ROOT}/llvm-libc++abi/libcxxabi/include" 
so the line 1039 must be `set( ANDROID_ABI_INCLUDE_DIRS "${ANDROID_CXX_ROOT}/llvm-libc++abi/libcxxabi/include" )`

**Comment by blair1618** [comment]
Good eye. Did you encounter an error related to this while building the library in a particular configuration?

**Comment by Oliver001** [comment]
I don't think it happens in a particular configuration. In fact, the file cxxabi.h in the path ${ANDROID_CXX_ROOT}/llvm-libc++abi/libcxxabi/include correctly.

**Comment by blair1618** [comment]
So it sounds like this isn't actually causing a problem with the build process. Is that correct?

The `android.toolchain.cmake` file was written by another open-source project, not by us, so I don't want to modify it unless we are very confident that it is causing a problem.

**Comment by Oliver001** [comment]
It's up to you.
Can you tell me the android.toolchain.cmake file was written by which open-source project?

**Comment by karimnaaji** [comment]
Hi @Oliver001 , I remember adding the support for c++ shared a while back https://github.com/tangrams/tangram-es/commit/67f04114b818f6bee392727d00a68d17e26b74c9 (and the cmake file was originally taken from the project you mentioned).

Unfortunately, this part might not work for all the android NDKs since it's highly adapted for our needs, we will be more specific in our README and specify that we currently develop under android-r10e NDK (https://github.com/tangrams/tangram-es#android).

We are also waiting for the new android studio which has CMake support before investing time in adapting this toolchain for all configurations (Refer https://github.com/tangrams/tangram-es/issues/807).

**Comment by blair1618** [comment]
We got the toolchain file from https://github.com/taka-no-me/android-cmake but then had to make some additions and corrections, and actually that line you pointed out was one of the things we added! After realizing that and testing the include path, I went ahead and made the change you suggested: https://github.com/tangrams/tangram-es/commit/b979ac754cd83bb8566dbfc6e1e09a6d506ff28b

**Comment by Oliver001** [comment]
Hi @karimnaaji,  the new stable android studio which has CMake support maybe release after two month or later.  
Thanks.
