### ISSUE TITLE
Support for webp raster data.

### ISSUE THREAD

**Issue by lygstate** [tangrams/tangram-es#880]

**Comment by bcamper** [comment]
Hi @lygstate - while we would like to support the most popular image formats, since WebP is currently only supported by [Chrome/Chromium-based browsers](http://caniuse.com/#search=webp), I don't feel that it clears this bar at this time.

Though I have not tried it, WebP images used in Tangram JS should load fine in Chrome.

For Tangram ES, you could look at adding support in a fork, and we might consider a Pull Request if you're interested though I will defer to @blair1618 on that.

**Comment by blair1618** [comment]
Interesting idea! WebP has some nice theoretical advantages over JPG and PNG, but like Brett said it's unlikely that we would want to include built-in support for WebP in tangram-es right now, simply because support in viewing and editing software is relatively scarce. 

The usable image formats in tangram-es are currently those that can be decoded by [stb_image](https://github.com/nothings/stb/blob/master/stb_image.h). Supporting WebP would require compiling an entirely new decoding library, and that burden doesn't seem worth the payoff for us.
