### ISSUE TITLE
I've create a newly project called glproxy, we could be able to link to it statically

### ISSUE THREAD

**Issue by lygstate** [tangrams/tangram-es#904]
https://github.com/glproxy/glproxy
There is only source files in glproxy, so we could be able to include and compile it.

This could used to replace https://github.com/tangrams/tangram-es/blob/master/core/src/gl.h,
And we could load the OpenGL Dynamic Libraries Dynamically, no need link to those libraries statically.
By using glproxy.

And this solved a issue, When I was trying to embed the tangram-es into QT.
Because Qt have a dynamic OpenGL runtime.

**Comment by blair1618** [comment]
I took a look at glproxy and I have some questions/concerns:

1. `glproxy.h` seems to define the OpenGL API for *every single version of OpenGL, including OES and vendor extensions*. This makes for a very, very, very large header file, which will slow down compilation quite a bit. Also, defining and trying to load multiple OpenGL APIs is at best unnecessary and at worst dangerous, because a program can only ever have *one* context from *one* API active at any given time. 

2. glproxy seems to include and try to load lots of extensions, both official and vendor-provided. However, it doesn't seem to provide any way to query whether those extensions are available at run-time so there's no way to use them safely (that is, there's no way to write fallback code for contexts where some extension isn't available). 

I appreciate the offer to make use of glproxy, but there are already tried-and-true OpenGL loaders and loader-generators available, like [GLAD](https://github.com/Dav1dde/glad) and [GLEW](http://glew.sourceforge.net/), and at this point I would choose to use one of those projects for dynamic OpenGL loading.

**Comment by lygstate** [comment]
@blair1618 GLAD& GLEW has problems that they do not compatible  BOTH OpenGL/OPENGL ES at the same time.

**Comment by lygstate** [comment]
@blair1618 And also, for some platform, we also need the platform depends functions, such as APPLE suffix and NV suffix or AMD suffix.
