### ISSUE TITLE
Feature Selection

### ISSUE THREAD

**Issue by hallahan** [tangrams/tangram-es#905]
As discussed in #748, we currently can select labels, but not the underlying points, lines, and polygons. To create an OSM editor or see properties associated with a map feature, we need to be able to select that feature from a tap event.

Looking at Tangram JS, we already have [this functionality](https://github.com/tangrams/tangram/blob/master/src/selection.js). It's an interesting solution, where we have a frame buffer that stores an identifier to a feature in a given pixel. 

Looking at Tangram ES, you have a custom 2d intersection library, [isect2d](https://github.com/tangrams/isect2d) being used for label selection--a really neat approach. This might be useful also for making rendering decisions from feature collision detection?

In the past, for this sort of thing, I've indexed features in an R-Tree or QuadTree, queried, and then done an intersection test.

What are your current thoughts on the best path forward for feature selection?

**Comment by bcamper** [comment]
Thanks @hallahan - the re-use of collision system in ES for feature picking was initially done as a matter of convenience, because we needed a subset of the full feature selection functionality on a short timeline and weren't yet ready to do the implementation for feature picking on every object. But our expectation has always been to extend this to all features.

I think I favor implementing the selection buffer approach from Tangram JS in ES as well, to maintain closer behavioral parity. That said, there are certainly arguments for both approaches, as well as unique needs on mobile that would have to be factored into the selection buffer method, such as a larger "touch area" for smaller features (this *could* be done with a selection buffer).

I will let @blair1618 weigh in with additional considerations.

**Comment by hallahan** [comment]
Regarding a "touch area" for smaller features, I'm thinking of two ways of going about this. One idea is to create geometric buffers around your points, lines, and polygons (making everything a polygon). You could then use those geometries for your selection buffer.

However, one trick I've done in the past that lets you avoid that is to actually create a geometric buffer around the touch point--a touch area polygon. Then, you would query several of the pixels in the selection frame buffer or do a collision test for that touch area polygon. This would be easier and require less computation upfront...

Since several features may be selected from the polygon of a touch area, we'd probably also want to implement selection priorities for features based off of certain things. One simple way of doing that is to priorities points over lines over polygons. Maybe how that is done could be specified in the scene file?

**Comment by bcamper** [comment]
Selection priorities is an interesting idea. I would probably start with using the existing `order` values to determine priority, and then see if that is sufficient, or if an additional selection-specific parameter is needed?

**Comment by hallahan** [comment]
Makes sense. The highest `order` value sounds like it would be what the user wants to select in most cases. If you needed to do something weird like select a polygon under a bunch of points, for example, those points probably wouldn't be specified as selectable anyway...

**Comment by nvkelso** [comment]
FYI: We’ll probably start shipping baked in priority values for most `pois`
layer features in v1.0.0 vector tiles, you could crib from that server
config file to set custom priorities in raw XML loaded data? (It’s also
interesting to think about building OSM editing into an app using a base
like Eraser Map with an “Edit feature” option that would toggle into the
raw OSM mode?)

**Comment by karimnaaji** [comment]
https://github.com/tangrams/tangram-es/issues/948 is now merged, closing this.

**Comment by hallahan** [comment]
👍 Awesome work!
