### ISSUE TITLE
float zoom level

### ISSUE THREAD

**Issue by ivangorelow** [tangrams/tangram-es#910]
Nowaday tangram api is zooming previous tiles level to show float zoom level. Is it possible unzooming next level to show float level?

**Comment by blair1618** [comment]
To clarify, the current behavior in tangram-es is to show the tiles for zoom level Z when the view is within the range [Z, Z+1). This was chosen to match the behavior of tangram-js. I can imagine alternative schemes:
 1. zoom Z tiles are shown for views in the range [Z - 0.5, Z + 0.5)
 2. zoom Z tiles are shown for views in the range (Z - 1, Z]

I believe the reason for the current behavior is to reduce the number of tiles needed to cover the screen - this usually improves performance without a noticeable loss in visual quality because vector tiles scale nicely. @bcamper: do you know if there are other reasons for this behavior?

**Comment by bcamper** [comment]
Yes that's right, we previously experimented with the [Z - 0.5, Z + 0.5) approach, but generally that led to unnecessary feature density (and additional draw call performance hit) in the [Z - 0.5, Z] range. I've found the current behavior to be a better balance that still keeps the logic simple.

It's possible we might offer a way to customize this in the future (such as via a custom data source parameter to "remap" tile coordinates), but for now I anticipate keeping this behavior.
