### ISSUE TITLE
Max Tilt 

### ISSUE THREAD

**Issue by ac87** [tangrams/tangram-es#934]
Two suggestions:

A default max tilt to avoid this sort of thing:

![image](https://cloud.githubusercontent.com/assets/20557626/17998685/8f449792-6b6d-11e6-9210-f06d9cde152e.png)

API method to be able to specify the max tilt. For example an app might want to disable tilting to force the user into a top-down view only.

**Comment by blair1618** [comment]
Ah, yes that's a reasonable request :)

Some things to think about:

 - Should this be part of the scene file configuration? Tilting may make sense to decide on a per-scene basis. 
 - Some map engines have a maximum tilt that varies based on the zoom level, which can be very useful since tilting the map at very low zoom levels doesn't make much sense. We could enable this as a scene parameter that takes a "stops" value.

cc @bcamper

**Comment by bcamper** [comment]
I think a scene-level value like `max_tilt`, in the `scene` block, could be
useful. If there are any other potential constraints that could be
optionally grouped under a `view` block or something (that was the thinking
with `background` having a `color` component, though there haven't been any
other background properties needed so far... but maybe a skybox etc.).

**Comment by nvkelso** [comment]
+1

**Comment by blair1618** [comment]
How about `camera: max_tilt`?

**Comment by ac87** [comment]
camera makes a lot of sense. Hadn't even thought of varying stops but now you mention it, I can see it in other apps.
