### ISSUE TITLE
Support TMS-style tiled data sources

### ISSUE THREAD

**Issue by tallytalwar** [tangrams/tangram-es#971]
JS Work: https://github.com/tangrams/tangram/pull/401
More information: https://alastaira.wordpress.com/2011/07/06/converting-tms-tile-coordinates-to-googlebingosm-tile-coordinates/

**Comment by hallahan** [comment]
Yep. MBTiles spec stores the tiles in TMS schema. The schema we are using used to be called Google TMS, since Google was the first to do quad tiles in the way that we are doing it. Some developers like to pretend that Google doesn't exist. They call it XYZ schema 😉 

Here's the TMS Spec:

http://wiki.osgeo.org/wiki/Tile_Map_Service_Specification

Here's the code I do to make the y transformation:

https://github.com/hallahan/tangram-es/blob/ef3c49d6c6f695b69703c8ab3e3b308de411a671/core/src/tile/mbtilesTileTask.cpp#L46

It's a nice little 1-liner to get the job done! It just flips the y axis and gives you a number of the range in the opposite direction.

You can use Math.pow, but I think bitwise left shift is faster? (not that it matters)...

**Comment by tallytalwar** [comment]
Correct, the `wordpress` link also has the same conversion math. 

bitwise left still matters even with the current grade of fast machines :).
