### ISSUE TITLE
Face Culling of 3d buildings

### ISSUE THREAD

**Issue by sheikh-iffi** [tangrams/tangram-es#976]
Hi 

After the latest updates, the interior walls of 3d buildings are always visible when the camera is inside the building. Previously, they used to disappear and we could see through them. Is this a new feature? See the screenshot below. The camera is currently inside the interior of a building and as you can see the outside features are obscured by its interior walls.

![1](https://cloud.githubusercontent.com/assets/12157369/18583671/68655206-7c25-11e6-9497-c9da0d48746d.png)

I asked if this is a feature or not because it seems like a bug to me. Upon enabling the DebugFlag "tangram_infos", the behaviour returns to normal (as it used to be) as shown in the screenshot below. The camera is at the same place as it was in the previous screenshot and now the interior walls are transparent.

![2](https://cloud.githubusercontent.com/assets/12157369/18583678/705f6046-7c25-11e6-9564-9a8373c8f520.png)

Thanks

**Comment by blair1618** [comment]
Hey, thanks for the report - that's super interesting! I haven't noticed that behavior before, I'll see if I can get the same results. 

Do you happen to know which commit this started with? This is not something we intended to change.

**Comment by blair1618** [comment]
Yeah whoops, not sure when this stopped happening but the engine was never enabling back face culling in normal rendering. The fix was super simple! https://github.com/tangrams/tangram-es/pull/977

Curiously, culling becomes enabled when debug text is drawn (https://github.com/tangrams/tangram-es/blob/master/core/src/debug/textDisplay.cpp#L141), which explains why the behavior changed when you set that debugging flag :)
