### ISSUE TITLE
The mapzen server doesn't support for non-gzip downloading, and WinHTTP doesn't support for gzip

### ISSUE THREAD

**Issue by lygstate** [tangrams/tangram-es#981]
So enable the mapzen server to support downloading non-gzip file directly.

**Comment by blair1618** [comment]
gzip compression is almost universally supported among HTTP user agents (browsers and networking libraries) because it significantly improves download speeds for most types of files. For this reason, we would want tangram-es to support gzip-compressed HTTP responses as well. If WinHTTP does not support gzip compression, that makes it unsuitable for use with tangram-es.
