### ISSUE TITLE
Add callback for request completed in HttpHandler

### ISSUE THREAD

**Issue by sarahlensing** [tangrams/tangram-es#986]
We would like to provide metrics around tile load time as part of this ticket: https://github.com/mapzen/android/issues/164

Could we extend the `HttpHandler` to add a method to know when a request completes? Maybe something like this:
`public boolean onRequestCompleted(String url, boolean loadedFromCache, Callback cb)`

cc/ @blair1618 @tallytalwar

**Comment by blair1618** [comment]
You may be able to do this already. If you subclass `HttpHandler` you can override `OnRequest` and instead of enqueuing the request with the original callback ([like the existing implementation](https://github.com/tangrams/tangram-es/blob/master/android/tangram/src/com/mapzen/tangram/HttpHandler.java#L37-L41)) you can wrap that callback in your own callback that executes any measurement actions you care about. 

If that doesn't work or proves to be excessively complicated then we'll need to add to the `HttpHandler` interface. Let me know how it goes!

**Comment by sarahlensing** [comment]
That worked well, no need to update the `HttpHandler` interface after all. Thanks!
