### ISSUE TITLE
cache layers

### ISSUE THREAD

**Issue by ivangorelow** [tangrams/tangram-es#988]
I'd like to add to map 160000 layers. It takes a lot of time. Can I cache it? Or make it faster?

**Comment by blair1618** [comment]
That's quite a lot of layers.

Can you explain the what you're trying to do with the map? Maybe we can come up with a better way of using tangram-es that doesn't require so many layers.

**Comment by ivangorelow** [comment]
I'd like to show all parkings in my city

**Comment by ivangorelow** [comment]
Maybe I should create source file?

**Comment by blair1618** [comment]
How is this parking data formatted? If you are using the Android SDK, the easiest solution may be to put your geometry data into a GeoJSON file and use it as a single data layer. You would create a `MapData` from the `MapController` and then call something similar to `yourMapData.addGeoJson(yourParkingDataGeoJson)`. Hope that helps.

**Comment by ivangorelow** [comment]
could you give me a tutorial to create a geojson?

**Comment by blair1618** [comment]
I suggested using the GeoJSON method because I thought that your data might already be in that format. If your data is not already in GeoJSON format then you should use the other methods of `MapData` (https://mapzen.com/documentation/tangram/android-sdk/0.4/com/mapzen/tangram/MapData.html) to add your data to the map. For instance, if you have your parking data available as polygons in your program then you can add each of them to the map using `MapData$addPolygon`.

One thing to be clear about here: there is no need to add a _layer_ to the map for each _feature_ that you want to add to the map. In this case I believe a _feature_ would be an individual parking geometry. If you have 160000 geometries that you want to put on the map you can put those all in one layer. You would only need to create additional layers if you wanted different categories of features to be styled differently.

**Comment by ivangorelow** [comment]
I add to one layer, but adding take a lot of time

**Comment by blair1618** [comment]
I see, I was confused about what you were trying to do.

For this many features, the current behavior of `MapData` it is probably not very efficient. In the near future it is likely that we will change this behavior to something more like the code proposed in https://github.com/tangrams/tangram-es/pull/847. 

For now, I think the only way to speed up your data layer is to put your data into GeoJSON and create the layer with that. The GeoJSON spec is here: http://geojson.org/geojson-spec.html and there are other resources online for creating and working with GeoJSON data (such as http://geojson.io).
